### PR TITLE
[PS-2072] Browser Badge fixes

### LINKED ISSUE #4260: Badge counter has gone
### Steps To Reproduce

1. Go to any site with login credentials saved in bitwarden vault.

### Expected Result

The badge counter should appear on the extension icon indicating how many logins I have for the current web page.

### Actual Result

After the 2022.12.0 update the badge counter has vanished. It only appears the extension icon without any badge counter.

### Screenshots or Videos

_No response_

### Additional Context

I tested in several websites using the chrome standard mode (not incognito) and the badge counter didn't show up in any of them.

### Operating System

Windows

### Operating System Version

_No response_

### Web Browser

Chrome

### Browser Version

108.0.5359.125 (64-bit)

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by djsmith85**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Fixes #4260

The badge was not showing or updating it's state (logout/lock/match) across browser windows and also not always in private/incognito mode

## Code changes

I've tried to split up the commits and provide detailed explainations for the changes in the commit messages.
I also provided links to the old implementation prior to the update-badge work to show the regressions.

- **apps/browser/src/listeners/update-badge.ts:** Show and update badge on all windows (Chrome MV2/MV3 (both with and without incognito mode), Firefox: MV2 (with and without private mode)
- **apps/browser/src/background/main.background.ts:** Small fix for Firefox private mode

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

File: apps/browser/src/listeners/update-badge.ts [hunk 1]
```diff
@@ -81,41 +85,50 @@ export class UpdateBadge {
...
 
-    const tab = await this.getTab(opts?.tabId, opts?.windowId);
-    const windowId = tab?.windowId;
-
     await this.setBadgeBackgroundColor();
 
     switch (authStatus) {
       case AuthenticationStatus.LoggedOut: {
-        await this.setLoggedOut({ tab, windowId });
+        await this.setLoggedOut();
```
Comment (justindbaur) [inline apps/browser/src/listeners/update-badge.ts:92]: Smart, I do a similar thing in context menu where "no access" states just change everything instead of trying to be smart.

File: apps/browser/src/background/main.background.ts [hunk 2]
```diff
@@ -603,7 +603,9 @@ export default class MainBackground {
     return new Promise<void>((resolve) => {
       setTimeout(async () => {
         await this.environmentService.setUrlsFromStorage();
-        await this.refreshBadge();
+        if (!this.isPrivateMode) {
```
Comment (justindbaur) [inline apps/browser/src/background/main.background.ts:606]: This is actually only true when in Firefox private mode right? So we aren't unnecessarily keeping this from working in Chrome incognito right?

**Review by justindbaur — APPROVED** [review]
This looks really good, thanks for the explanation for the thought process in each commit. We should make sure that the sidebar is tested by QA to make sure there are no regressions around that.

File: apps/browser/src/background/main.background.ts (hunk 2 above)
Comment (djsmith85) [reply apps/browser/src/background/main.background.ts:606]: Yes, Chrome in incognito mode works fine, this is just for Firefox private mode.

File: apps/browser/src/listeners/update-badge.ts (hunk 1 above)
Comment (djsmith85) [reply apps/browser/src/listeners/update-badge.ts:92]: 😁
