### PR TITLE
[PM-18153] add support for importing some older / wonky card formats from msecure

### LINKED ISSUE #13325: msecure export fails (both CLI, web, and desktop apps)
### Steps To Reproduce

1. Make an msecure export
2. Run the following: 
```
❯ bw import msecurecsv  ~/Downloads/mSecure_Export_File.csv
Cannot read properties of undefined (reading 'split')
```

### Expected Result

no error

### Actual Result

error

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

macOS

### Operating System Version

_No response_

### Shell

Zsh

### Build Version

2025.1.3

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by alexrosenfeld10**
# Note

This is blocking me from migrating to BitWarden. I'd appreciate it if someone could merge and ship this in a release sometime before end of February, so that I can migrate over before my mSecure license requires renewing. Otherwise I'll wait another year to migrate to BW 🥲 

## 🎟️ Tracking

https://github.com/bitwarden/clients/issues/13325

## 📔 Objective

Fixes #13325 

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

File: libs/importer/src/importers/msecure-csv-importer.ts [hunk 1]
```diff
@@ -43,23 +43,34 @@ export class MSecureCsvImporter extends BaseImporter implements Importer {
...
         cipher.card.expMonth = month.trim();
         cipher.card.expYear = year.trim();
-        cipher.card.code = this.getValueOrDefault(this.splitValueRetainingLastPart(value[6]));
+        const securityCodeRegex = RegExp("^Security Code\\|\\d*\\|");
+        const securityCodeEntry = value.find((entry: string) => securityCodeRegex.test(entry));
+        cipher.card.code = this.getValueOrDefault(
+          this.splitValueRetainingLastPart(securityCodeEntry),
+        );
+
+        const cardNameRegex = RegExp("^Name on Card\\|\\d*\\|");
```
Comment (alexrosenfeld10) [inline libs/importer/src/importers/msecure-csv-importer.ts:52]: It's theoretically possible someone could put this in their custom note field, but in practice, I highly doubt anyone is going to. If they do... 🤷‍♂️ I guess this will blow up.

If anyone feels strongly, I can add a check to ensure only one match is found, and fail outright if so.

---

As a sidenote, it'd be a good refactor to make importers limp along. As in, if they encounter an error on a single import, don't fail the whole file. Instead, keep track of the failures, finish the import, and report back specifically which entries failed and why.

That's a bigger refactor than what I'm reasonably able to do right now though - I'll leave it to a maintainer 🙂

File: libs/importer/src/importers/msecure-csv-importer.ts [hunk 2]
```diff
@@ -43,23 +43,34 @@ export class MSecureCsvImporter extends BaseImporter implements Importer {
...
-          ": " +
-          this.getValueOrDefault(this.splitValueRetainingLastPart(value[10]), "") +
-          "\n" +
-          this.getValueOrDefault(value[11].split("|")[0]) +
-          ": " +
-          this.getValueOrDefault(this.splitValueRetainingLastPart(value[11]), "");
+
+        cipher.card.brand = this.getValueOrDefault(this.splitValueRetainingLastPart(value[9]), "");
+
+        const noteRegex = RegExp("\\|\\d*\\|");
```
Comment (alexrosenfeld10) [inline libs/importer/src/importers/msecure-csv-importer.ts:60]: same, another slightly fuzzy bit of logic, but realistically it's probably good enough

File: libs/importer/src/importers/msecure-csv-importer.ts [hunk 3]
```diff
@@ -43,23 +43,34 @@ export class MSecureCsvImporter extends BaseImporter implements Importer {
...
+        const rawNotes = value
+          .slice(2)
+          .filter((entry: string) => !this.isNullOrWhitespace(entry) && !noteRegex.test(entry));
+        const noteIndexes = [8, 10, 11];
```
Comment (alexrosenfeld10) [inline libs/importer/src/importers/msecure-csv-importer.ts:64]: I'll confess I have no clue what these indexes really refer to - just dovetailing with what the logic used to be

File: libs/importer/src/importers/msecure-csv-importer.ts [hunk 4]
```diff
@@ -95,6 +106,6 @@ export class MSecureCsvImporter extends BaseImporter implements Importer {
   // like "Password|8|myPassword", we want to keep the "myPassword" but also ensure that if
   // the value contains any "|" it works fine
   private splitValueRetainingLastPart(value: string) {
-    return value.split("|").slice(0, 2).concat(value.split("|").slice(2).join("|")).pop();
+    return value && value.split("|").slice(0, 2).concat(value.split("|").slice(2).join("|")).pop();
```
Comment (alexrosenfeld10) [inline libs/importer/src/importers/msecure-csv-importer.ts:109]: this is critical - all sorts of records can blow up here without the check.

**Comment by alexrosenfeld10** [comment]
@aj-rosado I noticed you were the last to edit these files, if you could kindly review this PR that'd be great.

**Comment by djsmith85** [comment]
Hi @alexrosenfeld10 and thank you very much for your contribution 🎉 

I currently can't promise that your changes will get reviewed and tested, in time for the next release. I have assigned myself and queued it up for detailed review. Briefly looking at it, I don't see any odd issues, especially since all previously existing tests are still passing.

As you already have made the changes you could use any of the build artifacts from the pipeline ([desktop](https://github.com/bitwarden/clients/actions/runs/13303998257) being the easiest to use) or build any of the clients locally and import your [mSecure data into Bitwarden](https://bitwarden.com/help/import-data/#import-to-your-individual-vault). This should unblock you from migrating.

Kind regards,
Daniel

**Comment by alexrosenfeld10** [comment]
Would be great if a maintainer could merge this

**Comment by alexrosenfeld10** [comment]
I ended up sticking w/mSecure, also seems like this isn't going to be merged. Closing it out.

**Comment by djsmith85** [comment]
@alexrosenfeld10 Sad to see you closing this. 

I did mention that it likely wouldn't make the next release. I also described a way to unblock you on your migration. 
I'm sorry I hadn't responded to your comment. Unfortunately I did get pulled into higher priority work, which made this sit longer than I'd hoped for.

All Community's PR are highly appreciated, especially the ones that fix bugs like this one. Unfortunately due to process, that Bitwarden is still working on to improve, they tend to sit longer than they should.  I am personally involved within a group committed to improving this process. One thing I think is missing, is more transparency around the process/progress for the contributors.

Possibly some more labels/comments to show the progress.

If you still would like to see this included, please re-open.

Kind regards,
Daniel

**Comment by alexrosenfeld10** [comment]
@djsmith85 oh hey - thanks for the response. 

I ended up sticking with mSecure partially because of this but also because of some other reasons (migrating my grandma is a learning challenge 🙂). Agreed there are workarounds I just didn't end up getting to it as it all rolled up to "maybe we don't do this right now"

Regarding release schedules - does that mean you don't merge PRs until the release comes out? If that's the case and this wasn't forgotten about, I'm happy to reopen the PR. I think it would be useful for anyone else in the future, possibly even myself.

**Comment by djsmith85** [comment]
Thank you for re-opening, I agree that this is a valuable contribution for anyone looking to migrate from mSecure.

No worries about the migration. I know it can be a hurdle to onboard non-technical people on to new tools. Any PW manager is better than none, though. Obviously I'm biased and hoping you'll reconsider Bitwarden next time around :) 

More detailed information around the contribution and review process [here](https://contributing.bitwarden.com/contributing/pull-requests/community-pr-process).
 
RE release schedules: 
First off some on information on [Bitwarden's branching strategy](https://contributing.bitwarden.com/contributing/pull-requests/branching#branching-for-release).
Any PR that was merged into `main` prior to the `rc`-cut will be included in a release. Unless something major is discovered during regression testing and would require a revert.
Merging into `main` will have required a code review and QA approval. Any work will need to be scheduled for review and QA (Sprint planning). Depending on when a PR gets merged it might not make a certain release window. As an example a day after `rc`-cut, could mean it being delayed for inclusion for up to 4 weeks(next major release).

As you can see there are quite a few places where things can get delayed, with either review or release of a contribution.

Kind regards,
Daniel

**Review by djsmith85 — APPROVED** [review]
@alexrosenfeld10 Thanks again for your patience in getting this reviewed.

Your changes are looking good. I have tested this successfully and created example files for QA. Once they approve, this PR can be merged and then your changes will be included in an upcoming release.

Kind regards,
Daniel

**Comment by djsmith85** [comment]
@alexrosenfeld10 QA has approved and this is ready to merge. The changes will be included in the next major release.

Thank you for your contribution, especially appreciate, fixing a bug and improving the experience for others wanting to migrate from mSecure.

Kind regards,
Daniel
