### PR TITLE
PM-21553: Added support for credential.toJSON()

### LINKED ISSUE #14334: bitwarden passkey chrome extension not work on oracle cloud
### Steps To Reproduce

1. login to oracle cloud
2. try add passkey

### Expected Result

should work like chrome google password manger 

### Actual Result

should work like chrome google password manger 

### Screenshots or Videos

Image

### Additional Context

_No response_

### Operating System

Linux

### Operating System Version

_No response_

### Web Browser

Chrome

### Browser Version

Version 135.0.7049.95

### Environment Versions

Version: 2025.3.2

SDK: 'main (50f5a17)'

Server version: 2025.4.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by abergs**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-21553

## 📔 Objective

This PR adds support for [.toJSON()](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/toJSON).

It's part of the spec, and also resolves #14334. 

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

File: libs/common/src/platform/services/fido2/fido2-utils.ts [hunk 1]
```diff
@@ -1,6 +1,46 @@
 // FIXME: Update this file to be type safe and remove this and next line
+
+import {
+  AssertCredentialResult,
+  CreateCredentialResult,
+} from "../../abstractions/fido2/fido2-client.service.abstraction";
+
```
Comment (coroiu) [inline libs/common/src/platform/services/fido2/fido2-utils.ts:7]: issue: Importing files from the broader application in this file causes the content-script to swell (that's why Cesar added a duplicated `bufferToString` at the bottom here). I'm not sure how much this particular import will affect the size, however. Could you check the compiled file?

suggestion: if we're only using some types from that file you can use `import type` which should (I think) guarantee that it does not affect the size at all

Comment (abergs) [reply libs/common/src/platform/services/fido2/fido2-utils.ts]: Great feedback, just using the types so I've updated to `import type`. I also verified [in the documentation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) that it get's fully remove when it's compiled to JS.

**Review by coroiu — APPROVED** [review]
@abergs shouldn't we also add support for https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/parseCreationOptionsFromJSON_static and https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/parseRequestOptionsFromJSON_static while we're at it?

**Comment by abergs** [comment]
> shouldn't we also add support for [developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/parseCreationOptionsFromJSON_static](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/parseCreationOptionsFromJSON_static) and [developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/parseRequestOptionsFromJSON_static](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/parseRequestOptionsFromJSON_static) while we're at it?

@coroiu While I like the spirit, I don't think there's any need for us to do so. Thos are static methods on the PublicKeyCredential type - which is not something we own/modify. Right?

**Review by coroiu — COMMENTED** [review]
@abergs Like you say, in most cases the browser will implement those functions, but we do have support for polyfilling https://github.com/bitwarden/clients/blob/287887d20b8b201d234bb207b654591f91b6d1a9/apps/browser/src/autofill/fido2/content/fido2-page-script.ts#L32-L49 where we define our own global WebAuthn classes

**Review by coltonhurst — APPROVED** [review]

**Comment by navaneeth-dev** [comment]
Why revert this commit? Any idea when it will be pushed to the Chrome Web Store?

**Comment by abergs** [comment]
@navaneeth-dev We just want to do a bit more QA testing before we ship this feature.
