### PR TITLE
PM-12102 | Fix LastPass importer not properly de-encrypting URLs

### LINKED ISSUE #11051: Firefox Extension import from LastPass fails with encrypted URLs
### Steps To Reproduce

1. Have a LastPass account with encrypted URLs. Note that that's something pretty recent.
2. Follow the instructions from https://bitwarden.com/help/import-from-lastpass/#tab-direct-import-7dsxR2Yah8mdGJAmQdYZea
  Note that I am _not_ using the `csv` import! I use the API / extension-based handshake import.
3. I have both the LastPass and Bitwarden browser extension for Firefox.
4. Follow the instructions for the import. Authentication etc. all worked and all passwords were imported. However, each entry in Bitwarden now as a long encrypted URI instead of the clear text version.

### Expected Result

I guess decrypt (or trigger decryption) of the Lastpass URIs (URLs).

### Actual Result

They were all encrypted and look like this.
image

### Screenshots or Videos

_No response_

### Additional Context

I also noticed that the flag "require master password re-prompt" wasn't imported properly. Should I file a separate issue for that?

### Operating System

macOS, iOS

### Operating System Version

Sonoma 14.6.1 (23G93)

### Web Browser

Firefox

### Browser Version

130.0 (64-bit)

### Build Version

Version: 2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by Tyrrrz**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12102

Closes #11051

## 📔 Objective

LastPass encrypts URLs of items in their vault. When importing, they need to be decrypted to appear properly.

I used [this code](https://github.com/detunized/password-manager-access/commit/213e966bb651e9323f5508c79568809da7a6ab83#diff-bef5fc4c400af83e7b83a90460331c45ad3be3db95756ac60597f4ba430a909fR52) as reference for my implementation.

## 📸 Screenshots

Before:

image

After:

image

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

File: libs/importer/src/importers/lastpass/access/services/parser.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export class Parser {
   /*
   May return null when the chunk does not represent an account.
   All secure notes are ACCTs but not all of them store account information.
-  
+
   TODO: Add a test for the folder case!
   TODO: Add a test case that covers secure note account!
```
Comment (Tyrrrz) [inline libs/importer/src/importers/lastpass/access/services/parser.ts:27]: I also couldn't find any existing tests for this parser. Should I leave it like that or add them?

Comment (djsmith85) [reply libs/importer/src/importers/lastpass/access/services/parser.ts:27]: Ideally you would add them. In the meantime I'm going to approve and move this to QA, so we can hopefully include the fix soon.

**Review by djsmith85 — APPROVED** [review]

**Comment by djsmith85** [comment]
Spoke with QA and merging this, to be included with the `rc`-cut and continue with any further testing there.
