### PR TITLE
[PM-1144] Fix last active (auto logout issue)

### LINKED ISSUE #2482: Firefox on macOS: Vault locks immediately after unlocking
### Steps To Reproduce

Observed with version 1.57.0, Firefox (latest), macOS 12.3.

1. Configure the Firefox plugin to unlock with biometrics
2. Set the vault timeout to a time-based value
3. Let the plugin lock
4. Unlock the plugin through biometrics
5. Wait.

### Expected Result

The plugin stays unlocked.

### Actual Result

The plugin locks within 0–3 seconds.

### Screenshots or Videos

_No response_

### Additional Context

The issue does not occur if the vault timeout is set to "on browser restart". 

The issue does not occur consistently. In rare situations (for example, when locking manually for testing purposes), I observed that the vault remains unlocked after biometric unlock.

Related: https://community.bitwarden.com/t/firefox-vault-locks-immediately-after-unlocking/38478

### Operating System

macOS

### Operating System Version

12.3

### Web Browser

Firefox

### Browser Version

98.0.2

### Build Version

1.57.0

### PR DESCRIPTION
**Pull request by phyzical**
## Type of change

[x] Bug fix
[ ] New feature development
[ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
[ ] Build/deploy pipeline (DevOps)
[ ] Other

## Objective
fixes #2482 

There is a bug where the lastActive is not updated unless the following window level functions occur
```
 this.ngZone.runOutsideAngular(() => {
      window.onmousedown = () => this.recordActivity();
      window.ontouchstart = () => this.recordActivity();
      window.onclick = () => this.recordActivity();
      window.onscroll = () => this.recordActivity();
      window.onkeypress = () => this.recordActivity();
    });
```

But for example bio metrics login does not trigger these.

initially i just added a event to trigger a scroll for successful bio metrics login which solved the issue but there was other users that reported they do not use bio metrics that had the issue so i went about replicating the recordActivity functionality on a successful login instead

P.S Great get started docs was able to replicate and see what caused the issue within 15 minutes 👍 

Edit: turns out onblur works well enough from my testing

### CODE REVIEW

File: apps/browser/src/background/main.background.ts [hunk 1]
```diff
@@ -242,6 +242,7 @@ export default class MainBackground {
       this.stateMigrationService,
       new StateFactory(GlobalState, Account)
     );
+
```
Comment (phyzical) [inline apps/browser/src/background/main.background.ts:245]:
```suggestion
```

**Comment by phyzical** [comment]
I had a thought that there might just be another window level on event we could leverage and looks like onblur seems to work well enough

**Comment by MGibson1** [comment]
I agree that `onblur` makes some sense here, but I'm confused about why this is ocuring in the first place. [We should be recording  activity on login/unlock already ](https://github.com/bitwarden/clients/blob/master/apps/desktop/src/app/app.component.ts#L159).

It's possible the `activeUserId` is still null at this stage while unlocking, but I would love to unwrap that and either include a fix for that null issue in this, or keep the #2482 open until that problem is solved.

What do you think @phyzical? Did you already investigate why `recordActivity` on login/unlock was not preventing process reload?

**Comment by phyzical** [comment]
@MGibson1 hmm i dont think i checked specifically what that switch was reporting, but i can have a look this afternoon.

i wonder if ngRun is tied to the popup window being open maybe? so these logins close the window before the full swing of callbacks fire (total swing in the dark guess :D) 

But yeah ill have a closer scan around this piece of code as i don't remember seeing it when i was reviewing what could be the issue

**Comment by phyzical** [comment]
@MGibson1  had a quick look, spent 5 minutes debugging why i couldnt see the event thats firing, 

and then realized this code linked is on the desktop client, is it expected that a state update on the desktop client should then update the state of the browser client? 

(also this code was added after i started looking into the issue and thats why i never saw it)

i will have to spend a bit more time to workout how to build the desktop client locally to verify the linked code fixes it or not

**Comment by MGibson1** [comment]
Oh my, I've been thinking about the desktop the _entire_ time. I'm sorry. No, the two are totally unrelated when it comes to activity recording 😳 .

What it means is that we want to add a similar activity recording to the unlock/log in messages in browser as well. Should be a copy-pasta.

**Comment by phyzical** [comment]
i think thats what i did originally and felt it was a bit wrong :D @MGibson1 i will update the pr tonight if it isnt done already by then 👍

**Comment by phyzical** [comment]
@MGibson1 alright should be done now (i hope) i had to pipe up the "unlocked" message to the root messageService as thats where all the lastActive logic was run from lmk if there was  better way to go about this

i assume this check failure is unrelated to my changes as i dont remember it last time i pushed

**Review by MGibson1 — CHANGES_REQUESTED** [review]
Thank you for updating this, and I'm sorry for the delay. I take full responsibility there. I think there's a better way to grab the unlock event, using observables, but otherwise this seems right on the money 🥳 .

---
#### pipeline failure stuff 
The sonarcloud thing is some static code analysis we're trying out for early detection of possible security risks. I actually don't have access to determine exactly what it's complaining about... Something I've brought up as a feedback item 👎 .

Codescene is just reporting potential areas of high mental overhead. Useful to determine whether something is going to need some refactoring or love soon/now.

Both of those seem safe to ignore for the moment.

**Comment by phyzical** [comment]
@MGibson1 thanks for the hand hold, i think i have done it as suggested but i cant actually verify it as working due to a compilation error from master. i tried rejigging it to compile but no go.


image


lmk when this is resolved and i can test the changes to confirm it as working

**Comment by djsmith85** [comment]
That compiler error is from a [community PR](https://github.com/bitwarden/clients/pull/4479) which I merged recently. This only seems to come up locally and should go away once I get a chance to finish https://github.com/bitwarden/clients/pull/5070. The import/dependency then moves to libs/exporter instead of libs/importer.

**Comment by MGibson1** [comment]
Thank you @djsmith85!

For now, just replace the line with

```typescript
//eslint-disable-next-line
import { BitwardenPasswordProtectedFileFormat } from "../../../importer/src/importers/bitwarden/bitwarden-password-protected-types";
```

and you should be rocking and rolling. Fair warning: don't want to commit that, though

**Comment by MGibson1** [comment]
That's odd. You're right there are no errors there but surely if nothing is produced that's an error... Frustrating.

**Comment by djsmith85** [comment]
@phyzical, @MGibson1 #5070 has been reviewed and merged into master

**Comment by phyzical** [comment]
@djsmith85 thanks for the heads up, but still seem to be getting a bunch of errors relating to popup scss?

```
> @bitwarden/browser@2023.3.1 build /Users/phyzical/Sites/phyzical-clients/apps/browser
> webpack

Building Manifest Version 2 app
==================================================
envConfig
{
  "dev_flags": {},
  "flags": {
    "showPasswordless": true
  },
  "devFlags": {
    "storeSessionDecrypted": false,
    "managedEnvironment": {
      "base": "https://localhost:8080"
    }
  }
}
==================================================
main:
  assets by path _locales/ 3.8 MiB 58 assets
  assets by path images/ 66.5 KiB 21 assets
  assets by path popup/ 11.9 MiB 15 assets
  assets by path content/ 93.3 KiB 6 assets
  assets by path *.js 6.98 MiB
    asset vendor.js 3.54 MiB [compared for emit] (name: vendor) (id hint: commons2) 1 related asset
    + 2 assets
  assets by path notification/ 17.2 KiB
    asset notification/bar.js 8.97 KiB [compared for emit] (name: notification/bar)
    + 2 assets
  assets by path *.json 3.43 KiB
    asset manifest.json 2.94 KiB [compared for emit] [from: src/manifest.json] [copied]
    asset managed_schema.json 509 bytes [compared for emit] [from: src/managed_schema.json] [copied]
  asset background.html 161 bytes [compared for emit]
  orphan modules 479 KiB (javascript) 590 KiB (asset) 1.06 KiB (runtime) [orphan] 156 modules
  runtime modules 16.5 KiB 39 modules
  modules by path ../../ 7.44 MiB
    modules by path ../../node_modules/ 5.97 MiB 823 modules
    modules by path ../../libs/ 1.48 MiB
      modules by path ../../libs/common/src/ 1.05 MiB 419 modules
      modules by path ../../libs/angular/src/ 419 KiB 76 modules
      modules by path ../../libs/exporter/src/ 15.7 KiB
        modules by path ../../libs/exporter/src/vault-export/services/*.ts 14.8 KiB 2 modules
        ../../libs/exporter/src/vault-export/index.ts 110 bytes [built] [code generated]
        ../../libs/exporter/src/export-helper.ts 828 bytes [built] [code generated]
  modules by path ./src/ 1.48 MiB (javascript) 5.69 KiB (css/mini-extract) 179 modules
  fs (ignored) 15 bytes [built] [code generated]
  crypto (ignored) 15 bytes [built] [code generated]

  WARNING in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss)
  Module Warning (from ../../node_modules/sass-loader/dist/cjs.js):
  Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

  Recommendation: math.div($number, $number * 0 + 1) or calc($number / ($number * 0 + 1))

  More info and automated migrator: https://sass-lang.com/d/slash-div

  ../../node_modules/sweetalert2/src/scss/_core.scss 529:11  strip-units()
  ../../node_modules/sweetalert2/src/scss/_core.scss 531:13  @import
  ../../node_modules/sweetalert2/src/scss/_theming.scss 8:9  @import
  ../../node_modules/sweetalert2/src/sweetalert2.scss 4:9    @import
  src/popup/scss/plugins.scss 2:9                            @import
  src/popup/scss/popup.scss 11:9                             root stylesheet
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  WARNING in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss)
  Module Warning (from ../../node_modules/sass-loader/dist/cjs.js):
  Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

  Recommendation: math.div(strip-units($swal2-icon-size), 5) or calc(strip-units($swal2-icon-size) / 5)

  More info and automated migrator: https://sass-lang.com/d/slash-div

  ../../node_modules/sweetalert2/src/scss/_core.scss 531:13  @import
  ../../node_modules/sweetalert2/src/scss/_theming.scss 8:9  @import
  ../../node_modules/sweetalert2/src/sweetalert2.scss 4:9    @import
  src/popup/scss/plugins.scss 2:9                            @import
  src/popup/scss/popup.scss 11:9                             root stylesheet
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  2 warnings have detailed information that is not shown.
  Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 7:36-118
  Module not found: Error: Can't resolve '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.svg' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 8:36-118
  Module not found: Error: Can't resolve '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.ttf' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 9:36-119
  Module not found: Error: Can't resolve '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.woff' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 10:36-120
  Module not found: Error: Can't resolve '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.woff2' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 11:36-122
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/visa-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 12:36-122
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/amex-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 13:36-129
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/diners_club-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 14:36-126
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/discover-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 15:36-121
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/jcb-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 16:36-125
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/maestro-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 17:37-129
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/mastercard-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 18:37-128
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/union_pay-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 19:37-125
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/ru_pay-light.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 20:37-122
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/visa-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 21:37-122
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/amex-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 22:37-129
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/diners_club-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 23:37-126
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/discover-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 24:37-121
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/jcb-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 25:37-125
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/maestro-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 26:37-128
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/mastercard-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 27:37-127
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/union_pay-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss (./src/popup/scss/popup.scss.webpack[javascript/auto]!=!../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js!./src/popup/scss/popup.scss) 28:37-124
  Module not found: Error: Can't resolve '@bitwarden/angular/src/billing/images/cards/ru_pay-dark.png' in '/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss'
   @ ./src/popup/scss/popup.scss
   @ ./src/popup/main.ts 3:0-28

  ERROR in ./src/popup/scss/popup.scss
  Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
  HookWebpackError: Cannot find module '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.svg'
      at tryRunOrWebpackError (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/HookWebpackError.js:88:9)
      at __webpack_require_module__ (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:5058:12)
      at __webpack_require__ (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:5015:18)
      at /Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:5086:20
      at symbolIterator (/Users/phyzical/Sites/phyzical-clients/node_modules/neo-async/async.js:3485:9)
      at done (/Users/phyzical/Sites/phyzical-clients/node_modules/neo-async/async.js:3527:9)
      at Hook.eval [as callAsync] (eval at create (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
      at /Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:4993:43
      at symbolIterator (/Users/phyzical/Sites/phyzical-clients/node_modules/neo-async/async.js:3482:9)
      at processTicksAndRejections (internal/process/task_queues.js:77:11)
  -- inner error --
  Error: Cannot find module '@bitwarden/angular/src/scss/bwicons/fonts/bwi-font.svg'
      at webpackMissingModule (/Users/phyzical/Sites/phyzical-clients/node_modules/css-loader/dist/cjs.js!/Users/phyzical/Sites/phyzical-clients/node_modules/sass-loader/dist/cjs.js!/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss/popup.scss:19:113)
      at Module.<anonymous> (/Users/phyzical/Sites/phyzical-clients/node_modules/css-loader/dist/cjs.js!/Users/phyzical/Sites/phyzical-clients/node_modules/sass-loader/dist/cjs.js!/Users/phyzical/Sites/phyzical-clients/apps/browser/src/popup/scss/popup.scss:19:242)
      at /Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
      at Hook.eval [as call] (eval at create (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
      at /Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:5060:39
      at tryRunOrWebpackError (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/HookWebpackError.js:83:7)
      at __webpack_require_module__ (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:5058:12)
      at __webpack_require__ (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:5015:18)
      at /Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:5086:20
      at symbolIterator (/Users/phyzical/Sites/phyzical-clients/node_modules/neo-async/async.js:3485:9)
      at done (/Users/phyzical/Sites/phyzical-clients/node_modules/neo-async/async.js:3527:9)
      at Hook.eval [as callAsync] (eval at create (/Users/phyzical/Sites/phyzical-clients/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
      at /Users/phyzical/Sites/phyzical-clients/node_modules/webpack/lib/Compilation.js:4993:43
      at symbolIterator (/Users/phyzical/Sites/phyzical-clients/node_modules/neo-async/async.js:3482:9)
      at processTicksAndRejections (internal/process/task_queues.js:77:11)



  22 errors have detailed information that is not shown.
  Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

  main (webpack 5.76.1) compiled with 23 errors and 2 warnings in 47319 ms
  ````

**Comment by phyzical** [comment]
@MGibson1 after the fixes and fixing my node version i am able to confirm this fixes the issue

**Comment by phyzical** [comment]
ah i see you requested id3 metadata not just the lyrics im not super familiar so ill have to do a bit more reading on this..

File: apps/browser/src/popup/app.component.ts [hunk 2]
```diff
@@ -60,6 +60,12 @@ export class AppComponent implements OnInit, OnDestroy {
       this.activeUserId = userId;
     });
 
+    this.stateService.activeAccountUnlocked$
+      .pipe(takeUntil(this.destroy$))
+      .subscribe((unlocked) => {
+        unlocked ? this.recordActivity() : null;
+      });
```
Comment (MGibson1) [inline apps/browser/src/popup/app.component.ts:67]: Unfortunately `recordActivity` is async, which makes the subscription way more annoying. In general, we use [`concatMap`](https://www.learnrxjs.io/learn-rxjs/operators/transformation/concatmap) to handle awaiting things we need to subscribe to.

I think that's what we want here, too, because the order of the execution matters -- we don't want an earlier event to overwrite a later timestamp.

```suggestion
    this.stateService.activeAccountUnlocked$
      .pipe(
        filter((unlocked) => unlocked),
        concatMap(async () => {
          await this.recordActivity();
        }),
        takeUntil(this.destroy$)
      )
      .subscribe();
```

**Review by MGibson1 — CHANGES_REQUESTED** [review]

**Comment by phyzical** [comment]
@MGibson1 ah yep thanks for the suggestion, implemented and retested as working

**Review by MGibson1 — APPROVED** [review]

**Comment by MGibson1** [comment]
Excellent, thanks! I'll get this set up for internal QA testing and merge once that's completed. Might be a little while, QA is a little swamped at the moment prepping for a release.

**Comment by MGibson1** [comment]
Good news! This just passed QA. Thank you so much on iterating on this. I think we ended up with a nice fix. I appreciate your work on it.

**Comment by kapitainsky** [comment]
It took more than a year but if it works happy days. BW rocks.

**Review by MGibson1 — APPROVED** [review]
