### PR TITLE
Fix falling back to `data.json` when keyring is available

### LINKED ISSUE #8651: Error when syncing the vault on Linux desktop
### Steps To Reproduce

1. Go to 'File'
2. Click on 'sync vault'
3. Error sync vault

### Expected Result

sync vault

### Actual Result

Error sync vault

### Screenshots or Videos

_No response_

### Additional Context

I have installed version 2024.3.2 and can no longer synchronize the vault. I revert to 2024.3.0 and it works.
Server is self hosted.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04 LTS

### Installation method

Snap

### Build Version

"About Bitwarden" The application crashes 

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by tangowithfoxtrot**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-16856

## 📔 Objective

Fix #8651 and similar issues where, even if a secure storage keyring is available, we were falling back to `data.json`. We can't assume that the keyring is always unlocked when a user is logged in on Linux. This change ensures that we send an unlock prompt if the keyring is locked.

## 📸 Screenshots

The following demonstrates the happy path, where if the user's keyring was locked, we will consistently prompt them when we need to read or write keys.

Then, in the case where they decline the keyring prompts enough, we will force a de-authentication and fall back to insecure storage. However, users will continue to be prompted for their keyring if one is available, unless they choose to permanently deny our application access.

https://github.com/user-attachments/assets/ccba425f-fb3e-4604-a018-cef92865e020

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by quexten — APPROVED** [review]
LGTM

Non-blocking question to consider: Do we need to consider any retry logic here if the user enters the wrong password, or do gnome-keyring and kde wallet take care of this?

**Comment by tangowithfoxtrot** [comment]
> Non-blocking question to consider: Do we need to consider any retry logic here if the user enters the wrong password, or do gnome-keyring and kde wallet take care of this?

Good point. The keyring will reprompt if you enter the wrong password or decline the unlock request, but then we keep re-requesting the unlock anytime we do something with the access/refresh token, which is definitely not great. Let me see what needs to be done to make that a little nicer...

**Comment by tangowithfoxtrot** [comment]
> ...if the user enters the wrong password, or do gnome-keyring and kde wallet take care of this

@quexten, I tried to figure out a nicer way to look into a nicer way to handle incorrect passwords or declines to the keyring prompts, but I think that would require introducing some sort of `last_prompted` concept to our clients. The problem with doing that is that deciding _when_ to reprompt the user would feel kind of arbitrary.

So instead, I've made the prompt more consistent. It now applies to all keyring operations, except deletions. In the event that the user declines the prompt or enters incorrect passwords, we'll force a de-auth, and we'll call `delete_passwords` function to attempt the keyring, but it will fail silently when we do the deletes so we don't spam the user with prompts when we're just trying to clear the relevant credentials from the keyring.

I decided to silently fail in the deletion case (rather than prompting) because when we enter the forced de-auth state, we call attempt so many deletes that KDE will display a warning that an application is "misbehaving" by trying to access a locked keyring many times.

I feel like that might be the best balance of avoiding falling back as much as we can without being _too_ assertive with prompts if the user declines.

**Comment by quexten** [comment]
Thanks @tangowithfoxtrot! Sounds like a good solution. I'll re-review.

**Review by quexten — DISMISSED** [review]
Look good from my side, nice work! (But I'm not codeowner on the code).

File: apps/desktop/desktop_native/core/src/password/unix.rs [hunk 1]
```diff
@@ -62,13 +65,65 @@ pub async fn set_password(service: &str, account: &str, password: &str) -> Resul
...
 }
 
+/// Sends an OS notification prompt for the user to unlock/allow the application
+/// to read and write keys.
+async fn try_prompt(keyring: &oo7::Keyring) -> Result<bool> {
+    match keyring.unlock().await {
+        Ok(_) => Ok(true),
+        _ => Ok(false),
+    }
+}
```
Comment (dani-garcia) [inline apps/desktop/desktop_native/core/src/password/unix.rs:96]: This function never returns an error, so I don't think we need to return a Result. If we just want to ignore the unused result warning you can do that two ways:
```rust
let _ = keyring.unlock().await;
// or
keyring.unlock().await.ok();
```

**Review by dani-garcia — COMMENTED** [review]
LGTM, just one small nit

File: apps/desktop/desktop_native/core/src/password/unix.rs (hunk 1 above)
Comment (tangowithfoxtrot) [reply apps/desktop/desktop_native/core/src/password/unix.rs]: Makes sense. I think I missed this because the LSP is sort of wonky in the desktop_native stuff, so I didn't get warnings about unused Results 😅 

Let me know if the changes in https://github.com/bitwarden/clients/pull/12760/commits/8e7d2cf6dfc2741dc535dfbb955825fd8c97e22c are satisfactory, or if you'd prefer I drop the `bool` return value as well.

**Review by dani-garcia — APPROVED** [review]

**Review by quexten — APPROVED** [review]
