### PR TITLE
[PM-24289] fix popout windows on wayland (browser)

### LINKED ISSUE #9045: Popups not working under Wayland
### Steps To Reproduce

Try to open any Popup, for example:
1. The main popup from the extension menu on the top left
2. Clicking on "Unlock" when trying to autofill while the extension is still locked
3. Trying to log in with passkeys
4. Generally everything that requires a popup does not work

### Expected Result

A popup should appear

### Actual Result

No popup appears

### Screenshots or Videos

_No response_

### Additional Context

In the console of background.html this always appears:
Unchecked runtime.lastError: Invalid value for bounds. Bounds must be at least 50% within visible screen space.

When trying to log in with passkeys this also appears, but I don't know whether this is relevant:
[Fido2Client] Aborted by user: TypeError: Cannot read properties of undefined (reading 'id') 

### Operating System

Linux

### Operating System Version

Fedora 40 (Up-to-date)

### Web Browser

Brave

### Browser Version

1.65.126 Chromium: 124.0.6367.118

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### LINKED ISSUE #17837: Browser extension completely breaks passkeys/webauthn in browser process (Chromium/Linux)
### Steps To Reproduce

1. Go to https://webauthn.io
2. Click on `Register`
3. Scroll down to error message
4. `Error: The operation either timed out or was not allowed.`

This happens for all sites implementing webauthn, both for registration and auth.

Bizarrely, if I open devtools (as a separate window only, not as a docked pane), the browser extension works as expected and intercepts the call, popping the extension UI, and the native UI if the extension flow is cancelled.

If I disable the browser extension, the native webauthn UI is displayed correctly on register/auth.

### Expected Result

Browser extension pops to handle passkeys.

### Actual Result

Extension causes browser to return an error and completely breaks webauthn for the entire browser process.

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

Linux

### Operating System Version

`Arch Linux hostname 6.17.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:16 +0000 x86_64 GNU/Linux`

### Web Browser

Chrome

### Browser Version

142.0.7444.162

### Environment Versions

Version: 2025.11.1

SDK: 'main (8ef7951)'

Server version: 2025.11.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### LINKED ISSUE #19217: Unable to unlock with passkey on linux
### Steps To Reproduce

Try to unlock the browser extension with a passkey on linux

### Expected Result

The extension unlocks.

### Actual Result

The extension does not unlock.

### Screenshots or Videos

https://github.com/user-attachments/assets/7af57ee0-e450-4f8a-8a6d-3fb8340c3b4d

### Additional Context

If the extension is popped out from the browser window previously, then it does unlock with passkey.

I suspect this could be related to the bug fixed by [this PR](https://community.bitwarden.com/t/unable-to-login-to-browser-extension-chromium-with-passkey-on-linux/90916/4), that prevented login with passkey to the browser extension on GNU/Linux unless it was previously popped out.

Also, I'm not the only one hit by this bug: [1](https://community.bitwarden.com/t/unlock-with-passkey-does-not-unlock-unless-popped-out/93649?u=kpiris).

Thanks.

### Operating System

Linux

### Operating System Version

Debian trixie

### Web Browser

Chrome

### Browser Version

145.0.7632.116

### Environment Versions

Version: 2026.1.1
SDK: 'main (8e5efd8)'
Server version: 2026.2.0
(EU cloud server)
(Passkey stored on a YubiKey Bio)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by krjan02**
## 🎟️ Tracking

https://github.com/bitwarden/clients/issues/9045
https://github.com/bitwarden/clients/issues/18743

## 📔 Objective

Bitwarden's popup windows in the browser extension currently rely on precise `left` and `top` coordinates derived from the main browser window's position. While effective on X11, these coordinates are consistently reported as `0` by Chrome on Wayland, due to Wayland's design philosophy of abstracting global window positions from client applications.

This meant our popups were always appearing in the top-left corner of the screen on Wayland, instead of their intended relative position.

This commit introduces a check: if `senderWindow.left` and `senderWindow.top` are both `0` (indicating a Wayland-like environment), we explicitly set the new popup's `left` and `top` properties to 0. This allows the Wayland compositor to use its default placement logic for the window, ensuring it opens reliably and in a sensible location, rather than attempting to apply invalid coordinates.

For X11 and other environments where coordinates are valid, the original, precise positioning logic remains unchanged. This ensures consistent and functional popup behavior across different Linux display servers.

## 📸 Screenshots

image

## ⏰ Reminders before review

- Contributor guidelines followed ✅
- All formatters and local linters executed and passed ✅
- Written new unit and / or integration tests where applicable - Not applicable
- Protected functional changes with optionality (feature flags)  - Not applicable
- Used internationalization (i18n) for all UI strings  - Not applicable
- CI builds passed ✅
- Communicated to DevOps any deployment requirements 
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by esamson** [comment]
I have tested this on my local machine and can confirm that this patch resolves the popup issue on wayland.

Operating System: Fedora Linux 42
KDE Plasma Version: 6.4.4
KDE Frameworks Version: 6.17.0
Qt Version: 6.9.2
Kernel Version: 6.16.7-200.fc42.x86_64 (64-bit)
Graphics Platform: Wayland

Any chance of getting this merged soon?

**Comment by esamson** [comment]
I can confirm that issue still exists in `browser-v2025.10.0` and that this patch still resolves the issue.

**Comment by lynara** [comment]
any updates here? this bug is so annoying :(

**Comment by marshallford** [comment]
Any updates on this?

File: apps/browser/src/platform/browser/browser-popup-utils.ts [hunk 1]
```diff
@@ -145,17 +145,33 @@ class BrowserPopupUtils {
...
+
     const senderWindow = await BrowserApi.getWindow(senderWindowId);
-    const popoutWindowOptions = {
-      left: senderWindow.left + senderWindow.width - popupWidth - offsetRight,
-      top: senderWindow.top + offsetTop,
-      ...defaultPopoutWindowOptions,
-      ...windowOptions,
-      url: BrowserPopupUtils.buildPopoutUrl(extensionUrlPath, singleActionKey),
-    };
+    const waylandLike = senderWindow.left === 0 && senderWindow.top === 0;
```
Comment (trmartin4) [inline apps/browser/src/platform/browser/browser-popup-utils.ts]: @krjan02 would you mind adding some of the (excellent) comments that you included in the PR description here, so that that knowledge is conveyed in the code for the future?  Specifically around why Wayland-like environments are different, and how we're solving the problem by offloading responsibility for positioning to the compositor.

**Comment by Jamesking56** [comment]
Whats the best way to test these changes in my browser locally? I'm running Omarchy with Hyprland so would be nice to check if this works in this environment

**Comment by esamson** [comment]
@Jamesking56 - https://contributing.bitwarden.com/getting-started/clients/browser

File: apps/browser/src/platform/browser/browser-popup-utils.ts (hunk 1 above)
Comment (Alexandero89) [reply apps/browser/src/platform/browser/browser-popup-utils.ts]: @krjan02 sorry to pressure you, but could you maybe add the comments if you find some time?
I think the pr looks pretty good and it seems this is the final change needed so it will get merged.
Thanks!

Comment (throwaway8787) [reply apps/browser/src/platform/browser/browser-popup-utils.ts]: Actually the pressure should be on @trmartin4 to merge this, and then add a commit with the comment.

Comment (trmartin4) [reply apps/browser/src/platform/browser/browser-popup-utils.ts]: @throwaway8787 we will be addressing this ourselves if @krjan02 is not available to add comments as requested.  We are currently planning to address this soon, but we like to reach out to our contributors to make the changes first if they're available to do so.

File: apps/browser/src/platform/browser/browser-popup-utils.ts [hunk 2]
```diff
@@ -145,17 +145,33 @@ class BrowserPopupUtils {
...
+
+    let popoutWindowOptions: chrome.windows.CreateData;
+
+    if (waylandLike) {
```
Comment (lucemans) [inline apps/browser/src/platform/browser/browser-popup-utils.ts]:
```suggestion
    // The `senderWindow.left` and `senderWindow.top` are consistently reported as `0` by Chrome on Wayland, this is due to Wayland's design philosophy.
    // If waylandLike we explicitly reset the new popoutWindow's top and left, allowing the Wayland compositor to use its default placement logic for the window, ensuring it opens reliably and in a sensible location, rather than attempting potentially invalid coordinates.
    if (waylandLike) {
```

Comment (lucemans) [reply apps/browser/src/platform/browser/browser-popup-utils.ts]: @trmartin4 I've recomposed @krjan02 's original PR message into this comment.
Depending on github permissions you might be able to use the suggested change above.

Thank you for your attention to this, I look forward to having this fix rolled out to my systems 🙏

File: apps/browser/src/platform/browser/browser-popup-utils.ts (hunk 1 above)
Comment (throwaway8787) [reply apps/browser/src/platform/browser/browser-popup-utils.ts]: @trmartin4 this affects so much, like when you click to unlock a vault from an input, that popout never happens unless it's on your primary monitor. It makes it a real pita.

**Comment by Alexandero89** [comment]
@trmartin4 as i see it the comments are there and no functional code of the plugin is missing or needs to change.
If you find some time, could you please approve this so it gets merged for the next release.

its just a bit frustrating to see a bug fix which is so annoying to not be merged because of a comment in a code.
Thank you very much.

**Review by coroiu — APPROVED** [review]
