### PR TITLE
[PM-30447] ssoRequiredCache fix

### LINKED ISSUE #18439: Desktop client wrongly requires SSO if same email address is used with self-hosted instance
### Steps To Reproduce

1. Register an email address with Bitwarden online, with SSO
2. Register the same email address with a self hosted instance, without SSO
3. Sign in to Bitwarden online using SSO
4. Sign out
5. Try to sign in to Bitwarden self-hosted instance
6. Restart Bitwarden desktop client
7. Try to sign in to Bitwarden self-hosted instance

### Expected Result

The Bitwarden client recognises the self-hosted instance is not using SSO and allows for a regular master password log in.

### Actual Result

The Bitwarden client remembers that the email address was using SSO and continues to require it, even though it will not work with the self-hosted instance.  Restarting the client does not help.

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2025.12.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by rr-bw**
## 🎟️ Tracking

[PM-30447](https://bitwarden.atlassian.net/browse/PM-30447)

## 📔 Objective

Updates the `ssoRequiredCache` structure from `string[]` to `SsoRequiredCacheEntry[]`, which stores both the `email` and the `webVaultUrl` at the time of a successful SSO login.

This change was necessary because the previous `string[]` structure only stored email strings, but if a user used the same email to create an account on multiple different environments &mdash; where one account was required to use SSO and the other was not &mdash; then Extension and Desktop would fail to distinguish between these two accounts. Extension/Desktop would simply see that the email is in the cache, and then disable alternate login buttons any time that email was entered, regardless of environment (i.e. regardless of whether the user was truly required to use SSO.)

The new `SsoRequiredCacheEntry[]` format allows us to distinguish between accounts that have the same email, but are created on different environments and therefore might have dissimilar SSO Required policies applied.

### Cache Migration

Client has a pre-existing `ssoRequiredCache` with the old format (`string[]`) in storage. This cache
is now effectively ignored (it no longer disables alternate login buttons). Upon SSO login, the old format is
cleared and replaced with the new `SsoRequiredCacheEntry[]` format. Upon subsequent logins, the alternate
login buttons are disabled.

https://github.com/user-attachments/assets/c5d6908d-1f18-4539-84d0-eb98a79a1053

<br />

### Web - Create and populate cache (with a remembered email)

Video shows the following:
- When there is no existing `ssoRequiredCache`, it gets created and populated upon SSO login.
- When there is a pre-filled remembered email, the `ssoRequired` state will be reflected by
  disabling the alternate login buttons.
- Changing the email field re-runs the check for `ssoRequired`

https://github.com/user-attachments/assets/cdc7dfbd-9622-4c04-928a-e54df432f30d

<br />

### Extension - Add to cache and re-evalutate `ssoRequired` state on environment switch (with a remembered email)

Video shows behavior when there is a user with the same email on two different environments. One user is required to login with SSO, the other is not. Switching environments with a pre-filled/remembered email will cause the `LoginComponent` to re-evaluate the `ssoRequired` state upon an environment change.

https://github.com/user-attachments/assets/3bc84301-385f-42cb-a5c9-87c6ce31eaeb

<br />

### Desktop - Add to cache and re-evalutate `ssoRequired` state on environment switch (with a remembered email)

Video shows behavior when there is a user with the same email on two different environments. One user is required to login with SSO, the other is not. Switching environments with a pre-filled/remembered email will cause the `LoginComponent` to re-evaluate the `ssoRequired` state upon an environment change.

https://github.com/user-attachments/assets/9f73a90d-c4f3-461e-9f40-af45c30dacba

<br />

### Web - Enable and Disable SSO Required Policy (different emails, same environment)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `differentuser@local.dev`, WebVaultUrl: `https://localhost:8080`

Description:
- Video starts with `differentuser@local.dev` in the cache on env `https://localhost:8080`
- User5's org enables the Require SSO policy. User5 logs in with SSO and gets added to the cache - alternate login buttons disabled.
- User 5's org disables the Require SSO policy. User5 logs in with SSO and gets removed from the cache - alternate login buttons enabled.
- Meanwhile, `differentuser@local.dev` still sees login buttons disabled (their entry was correctly untouched).

https://github.com/user-attachments/assets/817a5952-0f8e-4931-9fde-155013e23af9

<br />

### Web - Leave Org (different emails, same environment)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `differentuser@local.dev`, WebVaultUrl: `https://localhost:8080`

Description:
- Video starts with both `user5@local.dev` and `differentuser@local.dev` in the cache (on the same environment)
- User5 leaves the org and gets removed from the cache - alternate login buttons enabled
- Meanwhile `differentuser@local.dev` still sees login buttons disabled (their entry was correctly untouched)

https://github.com/user-attachments/assets/bb37e538-e9ff-4b4f-93d1-92932a7f199e

<br />

### Web - Unlink SSO (different emails, same environment)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `differentuser@local.dev`, WebVaultUrl: `https://localhost:8080`

Description:
- Video starts with both `user5@local.dev` and `differentuser@local.dev` in the cache (on the same environment)
- User5 unlinks SSO and gets removed from the cache - alternate login buttons enabled
- Meanwhile `differentuser@local.dev` still sees login buttons disabled (their entry was correctly untouched)

https://github.com/user-attachments/assets/d474a9da-e17d-4b8c-a64f-60a96388d07e

<br />

### Extension - Enable and Disable SSO Required Policy (same email, different environments)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `user5@local.dev`, WebVaultUrl: `https://differentenvironment.com`

Description: 
- Video starts with `https://differentenvironment.com` user in the cache.
- `localhost` user's org enables the Require SSO policy. `localhost` user logs in with SSO and gets added to the cache - alternate login buttons disabled.
- `localhost` user's org disables the Require SSO policy. `localhost` user logs in with SSO and gets removed from the cache - alternate login buttons enabled.
- Meanwhile `https://differentenvironment.com` user still sees login buttons disabled (their entry was correctly untouched)

https://github.com/user-attachments/assets/6ef594fe-9fa2-4add-9297-099ad2f94857

<br />

### Extension - Leave Org (same email, different environments)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `user5@local.dev`, WebVaultUrl: `https://differentenvironment.com`

`localhost` user leaves their org on Web, which does not remove their entry from Extension storage. On Extension, alternate login buttons remain disabled - this user is in a soft-lockout state on this device and must freshly install client to remove entry from cache.

https://github.com/user-attachments/assets/b4e0f40f-66c1-4ada-9e44-0bf1be185898

<br />

### Extension - Unlink SSO (same email, different environments)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `user5@local.dev`, WebVaultUrl: `https://differentenvironment.com`

`localhost` user unlinks SSO on Web, which does not remove their entry from Extension storage. On Extension, alternate login buttons remain disabled - but this user can still sign in with SSO because they are still a member of the org.

https://github.com/user-attachments/assets/09f41c5e-8f71-4ca0-8c95-f96e74800425

<br />

### Desktop - Enable and Disable SSO Required Policy (same email, different environments)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `user5@local.dev`, WebVaultUrl: `https://differentenvironment.com`

Description: 
- Video starts with `https://differentenvironment.com` user in the cache.
- `localhost` user's org enables the Require SSO policy. `localhost` user logs in with SSO and gets added to the cache - alternate login buttons disabled.
- `localhost` user's org disables the Require SSO policy. `localhost` user logs in with SSO and gets removed from the cache - alternate login buttons enabled.
- Meanwhile `https://differentenvironment.com` user still sees login buttons disabled (their entry was correctly untouched)

https://github.com/user-attachments/assets/85f20bc2-25b7-4199-be36-10912657a187

<br />

### Desktop - Leave Org (same email, different environments)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `user5@local.dev`, WebVaultUrl: `https://differentenvironment.com`

`localhost` user leaves their org on Web, which does not remove their entry from Desktop storage. On Desktop, alternate login buttons remain disabled - this user is in a soft-lockout state on this device and must freshly install client to remove entry from cache.

https://github.com/user-attachments/assets/dced768b-22a7-4310-bcd9-07b6155ba04b

<br />

### Desktop - Unlink SSO (same email, different environments)

User's involved:
- Email: `user5@local.dev`, WebVaultUrl: `https://localhost:8080`
- Email: `user5@local.dev`, WebVaultUrl: `https://differentenvironment.com`

`localhost` user unlinks SSO on Web, which does not remove their entry from Desktop storage. On Desktop, alternate login buttons remain disabled - but this user can still sign in with SSO because they are still a member of the org.

https://github.com/user-attachments/assets/071be87e-454a-4355-b58e-b227c6c8a338

[PM-30447]: https://bitwarden.atlassian.net/browse/PM-30447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by rr-bw** [comment]
@nick-livefront the most relevant videos for Vault are the ones with "Leave Org" and "Unlink SSO" in the title.

File: apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts [hunk 1]
```diff
@@ -210,21 +212,30 @@ export class OrganizationOptionsComponent implements OnInit, OnDestroy {
...
+  /**
+   * Remove the user from the cached list of users who must authenticate via SSO (if an entry is present for the user)
+   */
+  private async removeUserFromSsoRequiredCacheIfPresent() {
     const activeAccount = await firstValueFrom(this.accountService.activeAccount$);
 
     if (!activeAccount) {
       this.logService.error("Active account not found.");
       return;
     }
```
Comment (nick-livefront) [inline apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts:228]: 🎨 ⛏️ This was existing and nit-picky (non-blocking): This could be condensed by using the `getUserId` helper and avoids having to throw a separate error:

```
const userId = await firstValueFrom(this.accountService.activeAccount$.pipe(getUserId));
```

**Review by nick-livefront — DISMISSED** [review]
Vault ✅ 

I appreciate all of the documentation around the different scenarios! Thank you 🙇

File: libs/common/src/auth/services/sso-login.service.ts [hunk 2]
```diff
@@ -149,51 +171,71 @@ export class SsoLoginService implements SsoLoginServiceAbstraction {
...
+
+          // Don't update if entry is already in the cache
+          return !cache.some((e) => this.entriesMatch(e, newEntry));
         },
       },
     );
   }
 
-  async removeFromSsoRequiredCacheIfPresent(email: string): Promise<void> {
+  async removeFromSsoRequiredCacheIfPresent(email: string, webVaultUrl: string): Promise<void> {
```
Comment (JaredSnider-Bitwarden) [inline libs/common/src/auth/services/sso-login.service.ts]: 🎨  : `removeFromSsoRequiredCacheIfPresent` could accept `userId` instead of `webVaultUrl` and resolve the URL internally via the already-injected `environmentService` similar to the `updateSsoRequiredCache` method. As more callers are added, each would otherwise need to duplicate the env lookup.

I think that would be cleaner, and it won't require a complete feature re-test - only a quick test of the unlink and leave org scenarios.

File: libs/common/src/auth/services/sso-login.service.ts [hunk 3]
```diff
@@ -61,34 +65,52 @@ export const SSO_EMAIL = new KeyDefinition<string>(SSO_DISK, "ssoEmail", {
...
+      // that format to infer the environment. New cache format uses SsoRequiredCacheEntry[].
+      // User will naturally populate the new cache format upon next SSO-required login.
+      if (typeof cache[0] === "string") {
+        return null;
+      }
+
+      return cache;
+    },
+  },
+);
```
Comment (JaredSnider-Bitwarden) [inline libs/common/src/auth/services/sso-login.service.ts]: 🎨 : at this point, the state part of this file has grown to the point it merits its own `sso-login.state.ts` file and corresponding `sso-login.state.spec.ts` file where we can write a test to cover this more complex deserializer branch since it has migration logic.

File: libs/common/src/auth/services/sso-login/sso-login.service.spec.ts [hunk 4]
```diff
@@ -99,92 +122,129 @@ describe("SSOLoginService ", () => {
...
+        // Act
+        await sut.updateSsoRequiredCache(email, userId);
+
+        // Assert
+        const cache = mockStateProvider.global.getFake(SSO_REQUIRED_CACHE);
+        expect(cache.nextMock).not.toHaveBeenCalled();
+      });
     });
 
     it("should check policy for correct PolicyType and userId", async () => {
```
Comment (JaredSnider-Bitwarden) [inline libs/common/src/auth/services/sso-login/sso-login.service.spec.ts:271]: ⚠️ : Please add a test to verify that `environmentService.getEnvironment$` is called with the correct `userId` in `updateSsoRequiredCache()`, similar to this test. This would ensure the right environment's `webVaultUrl` is used when building the cache entry — if the wrong user's environment were used, cache lookups could silently fail for that user.

**Review by JaredSnider-Bitwarden — CHANGES_REQUESTED** [review]
Everything is looking really nice! Thank you for all the thorough test scenarios! Just a few small tweaks and we are good to go!

File: libs/common/src/auth/services/sso-login.service.ts (hunk 2 above)
Comment (rr-bw) [reply libs/common/src/auth/services/sso-login.service.ts]: Updated both add and remove methods to take a userId - https://github.com/bitwarden/clients/pull/19879/changes/d006724d2c01a05f85e8f2cee909c3dda95ef871

File: libs/common/src/auth/services/sso-login.service.ts (hunk 3 above)
Comment (rr-bw) [reply libs/common/src/auth/services/sso-login.service.ts]: Resolved. See:
- `sso-login.state.ts`
- `sso-login.state.spec.ts`

And along with these, the `SsoLoginService` is now moved into an `sso-login/` folder.

File: libs/common/src/auth/services/sso-login/sso-login.service.spec.ts (hunk 4 above)
Comment (rr-bw) [reply libs/common/src/auth/services/sso-login/sso-login.service.spec.ts:271]: https://github.com/bitwarden/clients/pull/19879/changes/e7f16b745d3e9feba82c751240066d473aedbc14

**Comment by rr-bw** [comment]
@JaredSnider-Bitwarden Given the changes in https://github.com/bitwarden/clients/pull/19879/changes/d006724d2c01a05f85e8f2cee909c3dda95ef871 (updating both the `addToSsoRequiredCache()` and `removeFromSsoRequiredCacheIfPresent()` methods), I think I will need to retest most (if not all) of the feature. Before I re-record videos, let me know if you are happy with the direction of the PR. Note that I did also add the state migration.

**Review by dereknance — DISMISSED** [review]
Changes to Platform-owned files look good.

File: libs/common/src/auth/services/sso-login/sso-login.state.spec.ts
Comment (JaredSnider-Bitwarden) [inline libs/common/src/auth/services/sso-login/sso-login.state.spec.ts:1]: NIce! Thank you for testing this. Note: we should add a TODO here for https://bitwarden.atlassian.net/browse/PM-35145 to clean up the no longer relevant tests.

Comment (rr-bw) [reply libs/common/src/auth/services/sso-login/sso-login.state.spec.ts:1]: https://github.com/bitwarden/clients/pull/19879/changes/d2f5c23623c88a256e9e31cab483187ecf95dd4d

**Review by JaredSnider-Bitwarden — APPROVED** [review]
Excellent work. Thank you for iterating on this!

File: apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts (hunk 1 above)
Comment (rr-bw) [reply apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts:228]: I do need the email (a few lines below), so I don't think that would help us here.

**Review by dereknance — APPROVED** [review]

File: apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts (hunk 1 above)
Comment (nick-livefront) [reply apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts:228]: Ah! I missed that, thank you!

**Review by nick-livefront — APPROVED** [review]
