### PR TITLE
[PM-28091] - Add copy and quick launch action items

### LINKED ISSUE #20296: Copy toast shows word "Copy" twice on single field items
### Steps To Reproduce

1. Search for a password entry
2. click copy button

### Expected Result

Normal "copy password" toast is displayed

### Actual Result

The word 'Copy' appears twice Image

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

Windows

### Operating System Version

_No response_

### Web Browser

Firefox

### Browser Version

_No response_

### Environment Versions

```
Version: 2026.3.0

SDK: 'main (7637fdf)'

Server version: 2026.4.0
```

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by jaasen-livefront**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-28091

Defects
https://bitwarden.atlassian.net/browse/PM-35221
https://bitwarden.atlassian.net/browse/PM-35223
https://bitwarden.atlassian.net/browse/PM-35225
https://bitwarden.atlassian.net/browse/PM-35457

## 📔 Objective

Adds quick copy and launch actions to the web vault item row, surfaced on row hover. This replaces the copy/launch shortcuts that previously lived only in the three-dot options menu.

**Changes:**

- **New shared `VaultItemCopyActionsComponent`** (`libs/vault`) — extracts copy-action logic from the browser popup into a shared component usable across both web and browser. Exposes a `cipher` input and an optional `showQuickCopyActions` input (browser only) to control inline vs. combined display mode.

- **Web vault row** (`vault-cipher-row.component`) — when the feature flag is enabled, a hover-reveal row of icon buttons (launch website + copy actions) appears on each cipher row. The three-dot menu's copy/launch shortcuts are hidden in this mode. When the flag is off, the row reverts to the original behavior: copy/launch items inside the three-dot menu.

- **Browser popup** (`item-copy-actions.component`) — refactored to a thin wrapper around the new shared component, delegating `showQuickCopyActions` from `VaultPopupCopyButtonsService`.

- **Missing i18n keys** — added `copyInfoTitle`, `copyNoteTitle`, `noValuesToCopy`, and `launchWebsiteName` to the web locale (`apps/web/src/locales/en/messages.json`), which were previously browser-only.

- **Feature flag** `pm-28091-add-copy-and-quick-launch-actions` gates all new web behavior. Flag off = original three-dot menu copy/launch items. Flag on = hover-reveal inline actions.

## 📸 Screenshots

Copy/quick launch

https://github.com/user-attachments/assets/c96393f3-1742-4a89-9931-a009ec2d1d6a

Disabled state & Keyboard/tab navigation

https://github.com/user-attachments/assets/7760a8db-497b-4ab5-9bc9-3149915b8b8a

### CODE REVIEW

File: libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts [hunk 1]
```diff
@@ -0,0 +1,205 @@
...
+    JslibModule,
+    MenuModule,
+    CommonModule,
+    CopyCipherFieldDirective,
+  ],
+})
+export class VaultItemCopyActionsComponent {
+  // FIXME(https://bitwarden.atlassian.net/browse/CL-903): Migrate to Signals
+  // eslint-disable-next-line @angular-eslint/prefer-signals
+  @Input({ required: true }) cipher!: CipherViewLike;
```
Comment (shane-melton) [inline libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts]: ⛏️ Since we're introducing this as a new component, can we convert these to signals and avoid adding more FIXMEs.

File: libs/vault/src/components/item-copy-actions/item-copy-actions.component.spec.ts
Comment (shane-melton) [inline libs/vault/src/components/item-copy-actions/item-copy-actions.component.spec.ts:1]: 👍 Thanks for the tests! 🧪 🎉

File: libs/vault/src/components/item-copy-actions/item-copy-actions.component.html [hunk 2]
```diff
@@ -0,0 +1,210 @@
+<ng-container *ngIf="CipherViewLikeUtils.getType(cipher) === CipherType.Login">
```
Comment (shane-melton) [inline libs/vault/src/components/item-copy-actions/item-copy-actions.component.html]: ⛏️ (non-blocking): We want to move towards using the new `@if {}` template syntax instead of `*ngIf`

File: apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html [hunk 3]
```diff
@@ -79,180 +79,202 @@
...
-            {{ "archiveVerb" | i18n }}
+          <ng-container *ngIf="isSecureNoteCipher">
+            <button type="button" bitMenuItem appCopyField="secureNote" [cipher]="cipher">
+              <i class="bwi bwi-fw bwi-clone" aria-hidden="true"></i>
+              {{ "copyNote" | i18n }}
+            </button>
+          </ng-container>
+
+          <bit-menu-divider *ngIf="showMenuDivider"></bit-menu-divider>
+        }
```
Comment (shane-melton) [inline apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html:237]: 💭 Looking forward too getting rid of all these duplicated menus once the feature flag is removed 🎉

**Review by shane-melton — COMMENTED** [review]
Looks really good, nice work! Just a few nits around some FIXMEs that were copied over.

File: libs/vault/src/components/item-copy-actions/item-copy-actions.component.html (hunk 2 above)
Comment (jaasen-livefront) [reply libs/vault/src/components/item-copy-actions/item-copy-actions.component.html]: @shane-melton Was just working on this. ;) 
https://github.com/bitwarden/clients/pull/20059/commits/01512e6b7f477912f400471235d9ce43ec055c00

File: libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts (hunk 1 above)
Comment (jaasen-livefront) [reply libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts]: @shane-melton For `showQuickCopyActions` it makes sense to switch to signals but for `cipher`  we're type narrowing in the getters which means we'll need to declare `const cipher = this.cipher()` at the beginning of those getters so I'm not sure if it's worth it for this particular component. Thoughts?

Comment (shane-melton) [reply libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts]: What if we tweaked those helpers to accept a `CipherViewLike` parameter instead? Avoids the redundant `const cipher = this.cipher()` and still gets the type narrowing.

```typescript
get hasLoginValues() {
  return this.getNumberOfLoginValues(this.cipher()) > 0;
}

private getNumberOfLoginValues(cipher: CipherViewLike) {
  if (CipherViewLikeUtils.isCipherListView(cipher)) {
    return cipher.copyableFields.filter(...).length;
  }
  return [cipher.login.username, ...].filter(Boolean).length;
}
```

Comment (jaasen-livefront) [reply libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts]: I dig it. Fixed along with updated specs https://github.com/bitwarden/clients/pull/20059/commits/06c352127a8c8e3a6e2a6eca46686daa780a6d04

File: apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html (hunk 3 above)
Comment (jaasen-livefront) [reply apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html:237]: Totally! It's real busy with the feature flag logic.

**Review by shane-melton — DISMISSED** [review]
Looks good, nice work!

**Comment by jaasen-livefront** [comment]
@shane-melton Added [a fix](https://github.com/bitwarden/clients/pull/20059/commits/440fcb2ae6fa35ab73190077072515afef3eb2d1) to show the  icons in a focus state as well. Also resolved a nasty merge conflict as all the `ngIf` directive usage have just been update to `@if` in the vault.

**Review by shane-melton — DISMISSED** [review]

**Comment by jaasen-livefront** [comment]
@shane-melton One last [fix](https://github.com/bitwarden/clients/pull/20059/commits/d28be8ff342af77a5bcaf6791780cf959716eb3e) for an alignment issue in the table.

**Review by shane-melton — DISMISSED** [review]

File: libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+type CipherItem = {
+  /** Translation key for the respective value */
+  key: string;
+  /** Property key on `CipherView` to retrieve the copy value */
+  field: CopyFieldAction;
+};
+
+// FIXME(https://bitwarden.atlassian.net/browse/CL-764): Migrate to OnPush
+// eslint-disable-next-line @angular-eslint/prefer-on-push-component-change-detection
+@Component({
```
Comment (jrmccannon) [inline libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts:22]: Any new components we create should be OnPush

**Review by jrmccannon — CHANGES_REQUESTED** [review]

File: libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts (hunk 4 above)
Comment (jaasen-livefront) [reply libs/vault/src/components/item-copy-actions/item-copy-actions.component.ts:22]: Done! https://github.com/bitwarden/clients/pull/20059/commits/f948e7ba53758699209f1d043c9c5a1bac07bfd6

**Review by jrmccannon — CHANGES_REQUESTED** [review]
Looks like there's some build errors from the merge :(

**Review by jrmccannon — DISMISSED** [review]

**Comment by jaasen-livefront** [comment]
@shane-melton @jrmccannon Added a commit to address one last defect. Thanks for your help on this!

**Review by jrmccannon — APPROVED** [review]

**Review by shane-melton — APPROVED** [review]

**Comment by jaasen-livefront** [comment]
@shane-melton @jrmccannon Had to deal with some merge conflicts from main. If you wouldn't mind taking another look it would be much appreciated. Ty!

**Review by shane-melton — APPROVED** [review]

**Review by jrmccannon — APPROVED** [review]
