### PR TITLE
[PM-24015] Handle Send form empty password field properly

### LINKED ISSUE #15718: Creating a text send and
### Steps To Reproduce

1. Create a new Bitwarden Send (File or Text)
2. Add Name
3. Add File/Text
4. Add a password
5. Remove the password

### Expected Result

There is no password created for the Send

### Actual Result

There is a password created for the Send. The user must add a character and then remove the character before submitting the password to view the Send.

### Screenshots or Videos

https://github.com/user-attachments/assets/1cd77a99-39d4-4a11-a23d-1f507e3fa514

### Additional Context

I was also able to reproduce this behavior in the web interface.

### Operating System

macOS

### Operating System Version

15.5

### Web Browser

Microsoft Edge, Firefox, Chrome

### Browser Version

Version 138.0.3351.95 (Official build) (arm64), 140.0.4 (aarch64), Version 138.0.7204.158 (Official Build) (arm64)

### Environment Versions

Version: 2025.6.1

SDK: 'main (1fa0f7a)'

Server version: 2025.7.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by mcamirault**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-24015

Closes #15718

## 📔 Objective

Because we initialized the Send form with `null` in the password field but empty text input fields are always `""`, typing then deleting a password from the form would set the Send's password to `""`. This PR makes it so that Send passwords that are entirely whitespace or line terminators will be surfaced as `null` instead, ensuring they are handled properly.

Also added a test on the component to confirm the behavior and removed some handling from a higher-level component that may have been a previous partial fix to this issue.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

File: libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts [hunk 1]
```diff
@@ -112,18 +113,27 @@ export class SendOptionsComponent implements OnInit {
...
-          maxAccessCount: value.maxAccessCount,
-          accessCount: value.accessCount,
-          password: value.password,
-          hideEmail: value.hideEmail,
-          notes: value.notes,
+    this.sendOptionsForm.valueChanges
+      .pipe(
+        tap((value) => {
+          if (Utils.isNullOrWhitespace(value.password)) {
+            value.password = null;
```
Comment (harr1424) [inline libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts:120]: ❓ should this be `undefined`?   Sometimes `null` vs `undefined` can mean a behavioral difference.

File: libs/tools/send/send-ui/src/send-form/components/send-form.component.ts [hunk 2]
```diff
@@ -227,10 +226,6 @@ export class SendFormComponent implements AfterViewInit, OnInit, OnChanges, Send
       return;
     }
 
-    if (Utils.isNullOrWhitespace(this.updatedSendView.password)) {
-      this.updatedSendView.password = null;
```
Comment (harr1424) [inline libs/tools/send/send-ui/src/send-form/components/send-form.component.ts:231]: ❓ should this be `undefined`? Sometimes `null` vs `undefined` can mean a behavioral difference.

File: libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts (hunk 1 above)
Comment (mcamirault) [reply libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts:120]: I believe there's only two files where the password value is explicitly checked:
- [The `encrypt` method of the SendService](https://github.com/bitwarden/clients/blob/main/libs/common/src/tools/send/services/send.service.ts#L87). This uses loose equality so `null` vs `undefined` doesn't matter
- [The `hasPassword` method of the SendOptionsComponent](https://github.com/bitwarden/clients/blob/main/libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts#L76). This one does specifically check for `null` with strict equality, and there's a couple other operations in the same file that set the password value to `null` as well

Based on these I think `null` is the correct value to use

Comment (harr1424) [reply libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts:120]: Nice, the below is exactly what I had in mind: 
```typescript
  get hasPassword(): boolean {
    return this.originalSendView && this.originalSendView.password !== null;
  }
```
Great investigation, it is helpful to keep this in mind as other teams may open PRs that use `undefined`.

**Review by harr1424 — APPROVED** [review]
