### PR TITLE
[PM-32584] fix: warn user about unsaved changes before applying desktop update

### LINKED ISSUE #19121: on update, windows client loses non-saved entry and does not even warn user that it will be lost
### Steps To Reproduce

1. start a new item, don't save it yet
2. click system tray update notification
3. hit update
4. watch your stuff disappear instantly, no notification, no "are you sure you want to close bitwarden with an unsaved item?"

### Expected Result

Warn or stop user from losing data. Duh.

### Actual Result

Goes on and updates and loses all input.

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2026.1.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by bittoby**
## 🎟️ Tracking
https://bitwarden.atlassian.net/browse/PM-32584

Desktop client silently discards unsaved vault entries when auto-update restarts the app.

## 📔 Objective

When a user is editing or creating a vault item and an update is downloaded, clicking "Restart" in the update dialog immediately quits the app without warning — all unsaved form data is lost.

This PR adds an unsaved changes check before `quitAndInstall`. When the user clicks "Restart" and there are dirty form fields in the renderer, a warning dialog appears:

- **Title:** "Unsaved changes"
- **Detail:** "Are you sure you want to leave? If you leave now then your current information will not be saved."
- **Default button:** "Later" (protects user data by default)

If no forms are dirty, the update proceeds immediately with no extra dialog.

### How it works

- The main process queries the renderer via IPC (`hasUnsavedChanges` channel) before calling `quitAndInstall`
- The renderer checks for Angular's `.ng-dirty` class on any form element
- A 1-second timeout ensures the update is never blocked if the renderer is unresponsive
- Follows the existing `sdkVersion` IPC request/reply pattern
- Reuses existing i18n keys (`unsavedChangesTitle`, `unsavedChangesConfirmation`) — no new translations needed

### Files changed

- `apps/desktop/src/main/updater.main.ts` — guard before `quitAndInstall`, IPC query method
- `apps/desktop/src/platform/preload.ts` — IPC bridge for the new channel
- `apps/desktop/src/app/app.component.ts` — register dirty form check provider

### Issue: #19121

### CODE REVIEW

**Comment by Crystora** [comment]
@shane-melton @BTreston Could you please review this PR? I'd really thankful to give me any feedback.

**Comment by micahblut** [comment]
@bittoby thank you for your contribution! Can you please update the copy so it matches this design?
Screenshot 2026-02-26 at 10 03 24

**Comment by Crystora** [comment]
@micahblut Thanks for your feedback. i updated correctly to match your mock design. would appreciate you review again.

**Comment by Crystora** [comment]
@micahblut Any update for me

**Comment by micahblut** [comment]
> @micahblut Any update for me

Your contribution has passed internal review from product (that's me!) and will be reviewed by engineering soon.

File: apps/desktop/src/app/app.component.ts [hunk 1]
```diff
@@ -222,6 +222,26 @@ export class AppComponent implements OnInit, OnDestroy {
 
     this.authRequestAnsweringService.setupUnlockListenersForProcessingAuthRequests(this.destroy$);
 
+    ipc.platform.registerUpdateRestartHandler((resolve) => {
+      const hasDirtyForms = document.querySelectorAll(".ng-dirty").length > 0;
+      if (!hasDirtyForms) {
+        resolve(true);
+        return;
+      }
```
Comment (coroiu) [inline apps/desktop/src/app/app.component.ts]: We discussed this internally and eventually reached the conclusion that we think it's too brittle, relying on angular internals. If you're up for it, we have another design we would like to suggest:

We currently have [bit-submit.directive.ts](https://github.com/bitwarden/clients/blob/main/libs/components/src/async-actions/bit-submit.directive.ts#L31) which is intended to be used on all forms that don't auto-save while you type. We could add a `DirtyFormService` alongside it with which we could register our form groups.

```
// on init
DirtyFormService.registerFormGroup(someFoormGroup)

// on destroy
DirtyFormService.deregisterFormGroup(someFormGroup)
```

In the update restart handler we could then use 

```
DirtyFormService.hasDirtyForm()
```

which would check all the registered forms. What do you think?

File: apps/desktop/src/app/app.component.ts [hunk 2]
```diff
@@ -222,6 +222,26 @@ export class AppComponent implements OnInit, OnDestroy {
 
     this.authRequestAnsweringService.setupUnlockListenersForProcessingAuthRequests(this.destroy$);
 
+    ipc.platform.registerUpdateRestartHandler((resolve) => {
```
Comment (coroiu) [inline apps/desktop/src/app/app.component.ts]: I would like to avoid putting things in `app.component.ts`. Could you create a separate service and put this logic there instead? 

The `ipc.platform.registerUpdateRestartHandler` function call should be put in an `init` service which should be registered/called from the desktop `InitService`

**Comment by Crystora** [comment]
@coroiu I updated. Please review again. Thanks

File: apps/desktop/src/app/tools/send/add-edit.component.ts
Comment (harr1424) [inline apps/desktop/src/app/tools/send/add-edit.component.ts:1]: Changes to this file look good to me, I would like to get the opinion of our team's Angular expert @bmbitwarden before approving. Additionally, we have a lot of work planned in this file related to some new Send related functionality, so I apologize in advance for any merge conflicts that may soon result. 

Thanks for your contribution to Bitwarden, we look forward to working with you to get this improvement reviewed, tested, and merged.

**Comment by Crystora** [comment]
Thanks for letting me know @harr1424 . @bmbitwarden Could you please review my pr? I'd appreciate your feedback. 🙏

**Comment by Crystora** [comment]
Any updates for me, please

**Review by mcamirault — CHANGES_REQUESTED** [review]
Hi @bittoby, apologies for the lack of communication. There is [a cleanup PR in the works](https://github.com/bitwarden/clients/pull/19081) that is going to delete the `AddEditComponent` (among many other things) due to a recent refresh of the desktop Send UI. I'd recommend moving your changes to the `SendFormComponent` instead since it's going to be shared between all of our clients. The file is at `libs/tools/send/send-ui/src/send-form/components/send-form.component.ts`

**Comment by Crystora** [comment]
@mcamirault Thanks for providing essential feedbacks. I updated. Can you review again?

**Review by mcamirault — DISMISSED** [review]

**Comment by Crystora** [comment]
can you merge pr if it has no problem? @mcamirault

**Comment by harr1424** [comment]
@bittoby now that the relevant engineering team has approved your PR, it will be sent to QA for thorough testing. This process may take some time (right now I am thinking about one week, but this could change), and is described in greater detail [here](https://contributing.bitwarden.com/contributing/pull-requests/community-pr-process/).

**Comment by harr1424** [comment]
@bittoby my apologies, I spoke too soon and didn't realize other engineering teams still needed to give this a review. I've requested a re-review from @coroiu and reached out to our UI-Foundation team internally. Apologies for this mistake.

**Review by willmartian — DISMISSED** [review]
The UIF-owned code looks good to me! Thanks, @bittoby.

**Review by coroiu — COMMENTED** [review]
@bittoby There seem to be CI build(s) failing (ignore `* on PR Target`, these are expected to fail). I know these are hard to check as a contributor because of missing permissions, but there is a workaround: If you open a separate PR towards your own repository (with GH Actions enabled) you'll be able to trigger these builds yourself. You can use this to iterate on them before requesting a new review from us!

**Comment by Crystora** [comment]
@coroiu I fixed error. Others are permission error. Could you please check again? thanks

**Review by coroiu — DISMISSED** [review]
Looks good to me

**Comment by Crystora** [comment]
Would you please merge this PR? Thanks

**Comment by micahblut** [comment]
> Would you please merge this PR? Thanks

Again, the PR will be merged when it has passed the QA process, as documented in our[ contributing docs.](https://contributing.bitwarden.com/contributing/pull-requests/community-pr-process/)

**Comment by Crystora** [comment]
> > Would you please merge this PR? Thanks
> 
> Again, the PR will be merged when it has passed the QA process, as documented in our[ contributing docs.](https://contributing.bitwarden.com/contributing/pull-requests/community-pr-process/)

Ah, sorry. I forgot that. Thanks

**Review by willmartian — DISMISSED** [review]

**Review by mcamirault — DISMISSED** [review]

**Comment by Crystora** [comment]
@harr1424 @coroiu @mcamirault @willmartian Could you approve again? I have fixed type error. thanks

**Review by mcamirault — DISMISSED** [review]

**Comment by harr1424** [comment]
@bittoby please refrain from force pushing as this makes it considerably more time consuming to re-review your proposed changes, something we need to do before approving privileged CI checks to run.

**Review by harr1424 — DISMISSED** [review]

**Review by willmartian — DISMISSED** [review]
UIF changes still look good

**Review by coroiu — DISMISSED** [review]
I have marked the PR as Ready for QA. I'll update you when I get more information, please note that the QA process may take a while

**Comment by coroiu** [comment]
@bittoby The ticket was returned from QA with the following bug:

1. Log in > create (or edit) a cipher
2. While form is still up and has not been saved, click Bitwarden > Check for updates
3. Dialog prompt displays for installing Later or Restart
4. Click ‘Restart’
5. After several seconds the desktop app closes then reopens
6. Log back in
7. Notice your cipher isn’t create or the existing cipher does not contain your edits

I tried it myself and I can't get this dialog to appear either. Am I doing anything wrong?

https://github.com/user-attachments/assets/94b66ea7-1840-4b40-8be1-a07af4f3309c

**Comment by Crystora** [comment]
@coroiu Could you please review and test again? I have fixed. Thanks

**Comment by Crystora** [comment]
Any updates for me, please

**Comment by mcamirault** [comment]
Hey @bittoby just wanted to let you know that with the change in approach there are no longer any changes to files owned by the team @harr1424 and I are on. We're still happy to look over things but final approval should come from @coroiu and @willmartian

**Comment by Crystora** [comment]
@coroiu @willmartian Could you please take a look once more?

**Comment by Crystora** [comment]
@coroiu I submitted this PR about a month ago, even though it’s a simple change. What else should I need to update more? I hope to wrap up this pr soon

**Review by willmartian — APPROVED** [review]
Latest UIF changes look good to me. 

@bittoby, thanks again for your contribution. Please do keep in mind that all PRs (internal or external) must flow through multiple channels of review, testing, and approval. This can slow things down, but it helps ensure the security and quality of Bitwarden.

**Comment by coroiu** [comment]
Appreciate your patience. The fix you pushed still needs to pass through QA again before we can move forward. As Will mentioned, this process applies to all PRs (internal and external) and can take some time. We'll reach out when we have an update, no need to check in!

**Review by coroiu — APPROVED** [review]
QA approved, platform changes look good
