### PR TITLE
[PS-1874] Manage zoom factor when opening / closing the application

### LINKED ISSUE #2623: Zoom level not remembered on Ubuntu & Windows consistently
## Describe the Bug
The Bitwarden desktop application on Ubuntu does not remember zoom settings. My laptop display has a high resolution and so I need to be able to zoom for the UI to be legible. Setting the zoom level manually at the moment every time I start the app.

## Steps To Reproduce
1. Start Bitwarden desktop application
2. Login/Unlock account.
3. Set zoom level using menu bar or keyboard shortcut.
4. Close application.
5. Relaunch application.

## Expected Result
My previously set zoom level should be restored.

## Actual Result
The zoom level is reset to default making everything small again.

## Environment

- Operating system: Ubuntu 20.04
- Version: Version 1.20.1
- Shell: 6.1.7
- Renderer: 76.0.3809.146
- Node: 12.4.0
- Architecture: x64

## Additional Context
There appears to be some memory retention of the zoom level because when I try to zoom again it goes one level higher then what I've set. So I'm guessing the zoom level is remembered but not applied at startup?

This might not be a priority as it's not the responsibility of the application to deal with HiDPI screens(?), but since there is the option to set zoom levels, being able to remember it would be a big help. I'd be happy to help with the code if it isn't very complicated to fix.

### PR DESCRIPTION
**Pull request by CristianAUnisa**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix #2623
Zoom factor is saved into window state when closing the application and it's restored when opening it.
I'd like help with testing it on Windows and MacOS so I'm marking this as a draft pr.

## Code changes

- **window-state.ts:** Added optional zoomFactor property.
- **window.main.ts:** Added isClosing property to avoid assigning the zoomFactor property inside the window callbacks; wait for dom to be ready to restore the zoom factor.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

File: libs/common/src/models/domain/window-state.ts [hunk 1]
```diff
@@ -7,4 +7,5 @@ export class WindowState {
   displayBounds: any;
   x?: number;
   y?: number;
+  zoomFactor?: string;
```
Comment (djsmith85) [inline libs/common/src/models/domain/window-state.ts:10]: Based on the [docs](https://www.electronjs.org/docs/latest/api/web-contents#contentszoomfactor) `zoomFactor` should be of type `number`.

Because it's currently marked as string, this also throws an exception when the desktop app is first booted up. Likely because of this [line](https://github.com/bitwarden/clients/pull/4050/files#diff-87ddc677c70c152b6e5d783dbf2b629395d10ddedfe2cfdf2eaf971e4cc6988cR134)

File: libs/electron/src/window.main.ts [hunk 2]
```diff
@@ -13,6 +13,7 @@ const WindowEventHandlingDelay = 100;
 export class WindowMain {
   win: BrowserWindow;
   isQuitting = false;
+  isClosing = false;
 
   private windowStateChangeTimer: NodeJS.Timer;
   private windowStates: { [key: string]: any } = {};
```
Comment (djsmith85) [inline libs/electron/src/window.main.ts:19]: Using `WindowState` instead of any would give us types

File: libs/electron/src/window.main.ts [hunk 3]
```diff
@@ -45,6 +46,7 @@ export class WindowMain {
                   this.win.show();
                 }
                 this.win.focus();
+                this.win.webContents.zoomFactor = this.windowStates[mainWindowSizeKey].zoomFactor;
```
Comment (djsmith85) [inline libs/electron/src/window.main.ts:49]: I don't think this is necessary as the window should have rendered and set the zoomFactor initially

**Review by djsmith85 — CHANGES_REQUESTED** [review]
@CristianAUnisa Thank you for your contribution and great work on this, just some minor things.

Any specific reason to only apply the zoomfactor on "dom-ready" instead on window creation?

After adjusting the `zoomFactor`'s type to `number`: I can confirm that, the zoomFactor is remembered and applied, on application starts under Windows 🎉

**Comment by CristianAUnisa** [comment]
Hey, I'm going to fix the issues this afternoon, thank you for the answer.

Regarding why I used the dom-ready event, I tried with the win.on show, ready and many other ones but I always had some other issues; the zoom factor would be preserved but if I tried to increase or decrease it after starting the application, the zoom wouldn't be calculated from the zoom factor I set (imagine starting the application with a zoom of 150%, you increase it and the ui elements get smaller, like it was increased from 100% to 110%). I took inspiration from the Standard Notes code like two users reported in the issue and it felt the most reliable way of setting it, but unfortunately I only have a small notebook with Linux for now; I'm going to run the automated and manual tests again after the new changes, but would you prefer if I squash them into a single commit?

**Comment by djsmith85** [comment]
@CristianAUnisa 
Ah I see, but the [issue](https://github.com/electron/electron/issues/7779) you are referring to which gets mentioned on the [standardnotes-app](https://github.com/standardnotes/desktop/pull/355/files#diff-9dd2ef73375d4789f09ba7e171931d29ed03f909b40595a3837a25ae26c6440eR12), is from an ancient electron version. Very likely, this was fixed, and we do not need to rely on that event. It's worth testing, especially since the values (numbers) should now be assigned and persisted properly.

If we can remove the listener, we might also not need to the `isClosing`-flag. I'd appreciate if you could test out those ideas and if they work I'more than happy to review and test them.

If you can, please just push additional commits instead of squashing, as that would re-write git-history. My comments from the review, would still point to lines of code which you already addressed.

If this is good to go, the whole PR will get squashed anyway before merging into master.

File: libs/electron/src/window.main.ts (hunk 2 above)
Comment (CristianAUnisa) [reply libs/electron/src/window.main.ts:19]: May I ask you what do you mean in this context?

**Comment by CristianAUnisa** [comment]
@djsmith85 I tested the app again without the "dom-ready" listener without success:

- By setting the zoom factor attribute while creating the BrowserWindow in webContents
- By setting it after the window has been showed with win.show()

It didn't work; the window would show with a zoom factor saved probably from the closing event before the last one. The subsequent zoom factor is calculated based on the last zoom factor saved instead. I'm wondering about why this is happening because it feels like electron already attempts unsuccessfully to restore the previous zoom factor.

File: libs/electron/src/window.main.ts (hunk 2 above)
Comment (djsmith85) [reply libs/electron/src/window.main.ts:19]: I meant using the type `WindowState` instead of `any`. This will give us type-information for anywhere where we access `windowStates`.

```suggestion
  private windowStates: { [key: string]: WindowState } = {};
```

**Comment by CristianAUnisa** [comment]
@djsmith85 I pushed your suggestions. I'm trying again to find another way instead of listening to the "dom-ready" event. In the meanwhile, I could use WebContents.once instead of WebContents.on to remove the listener after the callback has been launched.

**Review by djsmith85 — CHANGES_REQUESTED** [review]
@CristianAUnisa I had another look at this today and played around with your code. I currently also see no other way of implementing this. Besides that your proposed solutions works fine 👍 .

Please pull in the lastest changes from master, resolving the merge conflict and I'll quickly re-review and then this should be ready to get passed on to QA.

Thank you for your time and great work on this ❤️

**Review by djsmith85 — APPROVED** [review]
@CristianAUnisa This is looking good and will now be passed on to QA for testing.

Once we get the approval from QA, this will get merged into `master`

**Comment by djsmith85** [comment]
@CristianAUnisa Just received approval from QA 🎉  This is ready to get merged and will be included in an upcoming release. 

Great work on this 👍
