### PR TITLE
[PM-18133] Remove generatePasswordCallback, rely on new service

### LINKED ISSUE #13208: Generator settings not honored by "context menu" and "export vault with password" flows
### Steps To Reproduce

Perform _both_ **Test A** and **Test B**.

##### Test A:
1. Open Generator view in the browser extension.
2. Set generation option to **"Password"**.
3. Modify the settings (e.g., number of characters, character classes, etc.).
4. In the browser, use the right-click context menu option **Bitwarden > Generate password (copied)**, then paste the clipboard to examine the generated password.
5. In the browser, use the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>9</kbd>, then paste the clipboard to examine the generated password.
6. In the extension, go to **Settings > Vault > Export Vault**, select the ".json (Encrypted)" format and the "Password protected" type, click the generate icon :arrows_counterclockwise: in the "File password" field, and then examine the generated password by clicking the toggle visibility icon :eye:.

##### Test B:
1. Open Generator view in the browser extension.
2. Set generation option to **"Passphrase"**.
3. Modify the settings (e.g., number of words, character separator, etc.).
4. In the browser, use the right-click context menu option **Bitwarden > Generate password (copied)**, then paste the clipboard to examine the generated password.
5. In the browser, use the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>9</kbd>, then paste the clipboard to examine the generated password.
6. In the extension, go to **Settings > Vault > Export Vault**, select the ".json (Encrypted)" format and the "Password protected" type, click the generate icon :arrows_counterclockwise: in the "File password" field, and then examine the generated password by clicking the toggle visibility icon :eye:.

### Expected Result

In  _both_ **Test A** and **Test B**, the three generated passwords obtained in Steps 4&ndash;6 should conform to the settings that had been configured in Steps 2&ndash;3.

### Actual Result

_Either_ **Test A** _or_ **Test B** fails, such that none of the three generated passwords obtained in Steps 4&ndash;6 honor the settings that had been configured in Steps 2&ndash;3.  If **Test A** works, then **Test B** will incorrectly generate passwords instead of passphrases; if **Test B** works, then **Test A** will incorrectly generate passphrases instead of passwords.

### Screenshots or Videos

_No response_

### Additional Context

This behavior is recent, although I do not know the exact version in which it started.  My tests used a Chrome browser, but other users have reported the same issue occurring in other browsers, in [this Community Forum thread](https://community.bitwarden.com/t/context-menu-password-generation-ignores-parameters/80264/).

### Operating System

Windows

### Operating System Version

Windows 11 (23H2)

### Web Browser

Chrome

### Browser Version

_No response_

### Build Version

Version: 2025.1.2; SDK: 'main (28c7e29)'

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by blackwood**
## 🎟️ Tracking

[PM-18133](https://bitwarden.atlassian.net/browse/PM-18133)

## 📔 Objective

Remove the `generatePasswordCallback`/`addPasswordCallback` bridge entirely. `OverlayBackground` no longer owns a password generation implementation — it now delegates to `CredentialGeneratorService.generate$()` via a reactive `Subject` pipeline with correct history tracking. `generatePasswordToClipboard` in `main.background.ts` is migrated to the new API as part of the same change. A `createCredentialGeneratorService` factory enables non-Angular-DI instantiation for the background service worker context.

[PM-18133]: https://bitwarden.atlassian.net/browse/PM-18133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/browser/src/background/main.background.ts [hunk 1]
```diff
@@ -2071,18 +2113,34 @@ export default class MainBackground {
...
-    const password = await this.generatePassword();
-    this.platformUtilsService.copyToClipboard(password);
-    await this.addPasswordToHistory(password);
-  };
+  generatePasswordToClipboard = () => {
+    // FIXME: `credentialGeneratorService` and `generatorHistoryService` are initialized in
+    // `initOverlayAndTabsBackground()`, which only runs for authenticated users. Returning EMPTY
+    // here preserves the pre-migration behavior (unauthenticated users could not generate passwords
+    // to clipboard), but this needs intentional assessment: should clipboard generation be allowed
+    // without authentication?
```
Comment (blackwood) [inline apps/browser/src/background/main.background.ts:2120]: FYI @jprusik

**Review by mcamirault — DISMISSED** [review]
Tools changes look good

**Review by mcamirault — APPROVED** [review]

File: apps/browser/src/background/main.background.ts (hunk 1 above)
Comment (jprusik) [reply apps/browser/src/background/main.background.ts:2120]: > should clipboard generation be allowed without authentication?

cc @wsalmon-bw

**Review by jprusik — APPROVED** [review]

**Comment by coolcoder613eb** [comment]
I'm waiting on this.

**Comment by coolcoder613eb** [comment]
Now that this is merged, when should I expect it to show up in my bitwarden extension?

**Comment by jprusik** [comment]
@coolcoder613eb The changes merged in here will tentatively go live at the start of May (some variability is involved due to the different extension stores' approval turnaround times).

**Comment by pamperer562580892423** [comment]
> will tentatively go live at the start of April (some variability

@jprusik Unless BW found a way to influence the past, I guess you meant to write "May"... 😉

**Comment by jprusik** [comment]
> > will tentatively go live at the start of April (some variability
> 
> @jprusik Unless BW found a way to influence the past, I guess you meant to write "May"... 😉

Indeed. Corrected 😅
