### PR TITLE
[PS-1335] problem with dropped letters keypresses when searching vault from browser extension debounce

### LINKED ISSUE #2371: Problem with dropped letters/keypresses when Searching vault from Browser extension (debounce)
### Environment

- Bitwarden 2022.6.x
- macOS 12.4
- Chrome 103

### Repro

1. click on bw icon in Chrome toolbar to open vault
2. start typing a search word— **_type fast_**
3. notice that midway through your typing, the field drops letters or garbles part of the word by overwriting the first few letters (this happens precisely when the preview/results area refreshes)

This might be a little hard to reproduce, but if you have a large enough vault (1000+ items) it shouldn't be too difficult. 

I think this is a debounce issue. The search function seems to run in a tight loop. It should run synchronously, and not drop keypresses so if typing quickly the search term is entered correctly.

### Expected Result

Search term e.g. "google" is entered completely

### Actual Result

Search sometimes gets entered as "goole" or "gogl" etc. due to dropped letters during refresh of results.

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Operating System

macOS

### Operating System Version

12.4

### Web Browser

Chrome

### Browser Version

103.0.5060.114

### Build Version

2022.6.3

### PR DESCRIPTION
**Pull request by dgoodman-bw**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
Fixes #2371 

The goal is to reduce the likelihood of typed letters getting skipped when searching from the Current Tab page on the browser extension.

## Code changes

Effectively, the only change should be increasing the debounce time of the search from 200ms to 500ms. 

The custom debounce implementation that used `window.setTimeout` has been replaced by an observables-based debounce implementation.

Also, the following autofocus implementation has been replaced with the `appAutofocus` directive. This is not related to the issue described in PS-1335; the intention was just to improve standardization. 
```
window.setTimeout(() => {
      document.getElementById("search").focus();
    }, 100);
```

This code changes in this PR do not completely eliminate the problem, but the frequency that it occurs should be greatly reduced. In order to resolve the issue completely, significant architectural refactoring would be required.

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

File: apps/browser/src/popup/vault/current-tab.component.ts [hunk 1]
```diff
@@ -40,6 +42,8 @@ export class CurrentTabComponent implements OnInit, OnDestroy {
   loaded = false;
   isLoading = false;
   showOrganizations = false;
+  search$ = new Subject<void>();
+  destroy$ = new Subject<void>();
```
Comment (djsmith85) [inline apps/browser/src/popup/vault/current-tab.component.ts:46]: This should be made private as it should only be accessible within this component

**Review by djsmith85 — CHANGES_REQUESTED** [review]
@dgoodman-bw: I tested this locally and it's definitely improved. Great work on this 👍 

Just one small thing and I think we are good to go.

**Review by djsmith85 — APPROVED** [review]
Looking good now!
