### PR TITLE
[SM-260] Fix #2800 - Handle already verified email when resending verification email

### LINKED ISSUE #2800: Verify Email Box does not update after verify
### Steps To Reproduce

1. Register
2. Open bitwarden homepage
3. Verify your email
4. See the "Verify Email" warning box

### Expected Result

Warning box should not show.

### Actual Result

Warning box is shown.

### Screenshots or Videos

Screen Shot 2022-01-14 at 22 02 43

### Additional Context

Refreshing the page does not fix the glitch. I had to clear local storage of the website.

### Operating System

macOS

### Operating System Version

12.1

### Web Browser

Firefox

### Browser Version

96.0.1

### Build Version

2.25.1

### PR DESCRIPTION
**Pull request by schang1146**
## Type of change

```
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective

Fix for #2800 where clicking the "Send Email" button in the warning box pops up an error telling the user that the email is already verified.

## Code changes

- **apps/web/src/app/settings/verify-email.component.ts**
Added some logic to check if an email is already verified or not when a user clicks on the "Send Email" button.
Added an EventEmitter to the verify-email component so that it can let its parent know that the email's already verified and that it can close the warning box.
Added code to pop-up a Toast briefly letting the user know that their email is verified.

- **apps/web/src/app/vault/vault.component.html**
Added the EventEmitter to the template to call a new function `updateVerifyEmail`.

- **apps/web/src/app/vault/vault.component.ts**
Added new function `updateVerifyEmail` to update `this.showVerifyEmail` variable.

Feel free to let me know if naming could be better 😅

## Screenshots

I'm getting better at this but the quality is poop.

https://user-images.githubusercontent.com/20074034/190708338-59206a2e-9f3b-4bd8-b601-32ea758a0e72.mp4

## Before you submit

- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

### CODE REVIEW

File: apps/web/src/app/settings/verify-email.component.ts [hunk 1]
```diff
@@ -12,17 +13,27 @@ import { PlatformUtilsService } from "@bitwarden/common/abstractions/platformUti
 export class VerifyEmailComponent {
   actionPromise: Promise<unknown>;
 
+  @Output() verifiedEmitter = new EventEmitter<boolean>();
```
Comment (Hinton) [inline apps/web/src/app/settings/verify-email.component.ts:16]: Angular convention is to prefix event emitters outputs `on`. What do you think about calling this `onVerified`?

File: apps/web/src/app/settings/verify-email.component.ts [hunk 2]
```diff
@@ -12,17 +13,27 @@ import { PlatformUtilsService } from "@bitwarden/common/abstractions/platformUti
...
-    private logService: LogService
+    private logService: LogService,
+    private tokenService: TokenService
   ) {}
 
   async send() {
     if (this.actionPromise != null) {
       return;
     }
+    await this.apiService.refreshIdentityToken();
```
Comment (Hinton) [inline apps/web/src/app/settings/verify-email.component.ts:30]: The purpose of the `actionPromise` is to lock the button from being pressed multiple times. We will need to add all async calls to that promise. I believe creating an async lambda function and putting all calls in it should work.

**Review by Hinton — CHANGES_REQUESTED** [review]
Hi @schang1146,

Thanks for the contribution! This looks like a great start. I've done an initial review and added a few comments.

File: apps/web/src/app/settings/verify-email.component.ts (hunk 1 above)
Comment (schang1146) [reply apps/web/src/app/settings/verify-email.component.ts:16]: I like that naming scheme. I'll make that change.

File: apps/web/src/app/settings/verify-email.component.ts (hunk 2 above)
Comment (schang1146) [reply apps/web/src/app/settings/verify-email.component.ts:30]: Ah gotcha, didn't look deep enough at what that was doing - my bad! Working on that now.

File: apps/web/src/app/settings/verify-email.component.ts (hunk 1 above)
Comment (schang1146) [reply apps/web/src/app/settings/verify-email.component.ts]: Renamed all instances of `verifiedEmitter` to `onVerified`.

File: apps/web/src/app/settings/verify-email.component.ts (hunk 2 above)
Comment (schang1146) [reply apps/web/src/app/settings/verify-email.component.ts:27]: Done with the changes, let me know what you think.

Added a `getIsVerified` async function to add to `actionPromise` that has all the calls needed to double check a user's email verification status.

File: apps/web/src/app/settings/verify-email.component.ts [hunk 3]
```diff
@@ -12,18 +13,37 @@ import { PlatformUtilsService } from "@bitwarden/common/abstractions/platformUti
...
   constructor(
     private apiService: ApiService,
     private i18nService: I18nService,
     private platformUtilsService: PlatformUtilsService,
-    private logService: LogService
+    private logService: LogService,
+    private tokenService: TokenService
   ) {}
 
+  async getIsVerified(): Promise<boolean> {
```
Comment (Hinton) [inline apps/web/src/app/settings/verify-email.component.ts:26]: Could we change this method to also include the `postAccountVerifyEmail`? That way all the async logic needed for the `actionPromise` happens here and there is no need to assign `actionPromise` multiple times.

 At the same time we should rename this function since we're no longer just checking if it's verified.

The end result would be something like:
```ts
async send()
  if (this.actionPromise != null)
		return;
	}
	
	try {
		this.actionPromise = this.verifyEmail()
	} catch (e) {
	  this.logService.error(e);
	}
	this.actionPromise = null;
}
```

File: apps/web/src/app/vault/vault.component.ts [hunk 4]
```diff
@@ -169,6 +169,10 @@ export class VaultComponent implements OnInit, OnDestroy {
     );
   }
 
+  updateVerifyEmail(bool: boolean) {
```
Comment (Hinton) [inline apps/web/src/app/vault/vault.component.ts:172]: We should look into a better name for this method. Since we are inverting the condition it's not a simple update. I think `emailVerified(verified: boolean)` might work better.

Comment (schang1146) [reply apps/web/src/app/vault/vault.component.ts]: Thanks for helping me with the naming. Pushed it up.

File: apps/web/src/app/settings/verify-email.component.ts (hunk 3 above)
Comment (schang1146) [reply apps/web/src/app/settings/verify-email.component.ts]: Yep, I grouped up the async logic into the (now-renamed) function `verifyEmail` so that we're only assigning to `actionPromise` and `await`-ing it once.

File: apps/web/src/app/settings/verify-email.component.ts [hunk 5]
```diff
@@ -12,25 +13,39 @@ import { PlatformUtilsService } from "@bitwarden/common/abstractions/platformUti
...
+      this.platformUtilsService.showToast("success", null, this.i18nService.t("emailVerified"));
+    } else {
+      await this.apiService.postAccountVerifyEmail();
+      this.platformUtilsService.showToast(
+        "success",
+        null,
+        this.i18nService.t("checkInboxForVerification")
+      );
+    }
+  }
```
Comment (Hinton) [inline apps/web/src/app/settings/verify-email.component.ts:39]: I typically prefer to use guards clauses here. But not a strong preference.

```suggestion
    if (await this.tokenService.getEmailVerified()) {
      this.onVerified.emit(true);
      this.platformUtilsService.showToast("success", null, this.i18nService.t("emailVerified"));
      return;
    }
    
    await this.apiService.postAccountVerifyEmail();
    this.platformUtilsService.showToast(
      "success",
      null,
      this.i18nService.t("checkInboxForVerification")
    );
  }
```

**Review by Hinton — APPROVED** [review]
I think this looks good, thanks for working through the review comments. Going to have our QA team test this before merging.

File: apps/web/src/app/settings/verify-email.component.ts (hunk 5 above)
Comment (schang1146) [reply apps/web/src/app/settings/verify-email.component.ts:39]: I like the suggestion! I don't mind making those changes, feel free to commit the suggestion or I can make them and test it out later tonight (PST time).

**Review by Hinton — APPROVED** [review]
Thanks!

**Comment by Hinton** [comment]
Merging this into a feature branch to let QA test it first.

**Comment by nikhilagastya** [comment]
hey is this issue still open?

**Comment by schang1146** [comment]
I think the issue's closed. Haven't heard further feedback that it's broken.

#2810 wasn't closed because the PR was linked after it was merged.

**Comment by djsmith85** [comment]
@schang1146 Thanks again for the contribution and for raising this.
@nikhilagastya I'm going to close #2810 but if the issue persists, please comment on there and we can re-open if needed

**Comment by nikhilagastya** [comment]
Sure @djsmith85 ,thanks alot !
