### PR TITLE
[PM-4077] safeincloud multiple url fix

### LINKED ISSUE #6269: Importing from "Safe in cloud" only imports the last of multiple URL fields
### Steps To Reproduce

1. Create safe in "Safe in cloud"
2. Create card with two or more fields `URL`
3. Export data from "Safe in cloud"
4. Import data to Bitwarden

### Expected Result

Entry in Bitwarden has all fields `URL` that were present in "Safe in cloud" and its export file.

### Actual Result

Entry in Bitwarden only has one (the last) field `URL`.

### Screenshots or Videos

_No response_

### Additional Context

Entry in export XML looks like this, so the export seems okay
```
  <card symbol="web_site" color="gray" template="false" star="false" id="1057250483" title="Jira + Confluence + Bitbucket" autofill="on" prev_stamp="1604997989005" time_stamp="1605007557602">
    <field name="Login" type="login" history="{&quot;1604916612662&quot;:&quot;&quot;}" autofill="username">bob</field>
    <field name="Passwort" type="password" history="{&quot;1604916612662&quot;:&quot;&quot;}" score="4" hash="...redacted..." autofill="current-password">...redacted...</field>
    <field name="URL" type="website" history="{&quot;1604916612662&quot;:&quot;&quot;}" autofill="url">https://jira.example.com/</field>
    <label_id>1244748074</label_id>
    <field type="website" name="URL" history="{&quot;1605007538920&quot;:&quot;&quot;}" autofill="url">https://confluence.example.com/</field>
    <field type="website" name="URL" history="{&quot;1605007538920&quot;:&quot;&quot;}" autofill="url">https://git.example.com/</field>
  </card>

```

### Operating System

Windows

### Operating System Version

10

### Web Browser

Brave

### Browser Version

1.57.62

### Build Version

n/a

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by sonigeez**
## Type of change

```
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other
```

## Objective
This PR addresses an issue where only the last of multiple URL fields was being imported. The aim is to ensure that all URL fields are imported correctly. 
Fix #6269 

## Code changes
- **safeincloud-xml-importer.ts:** Modified the logic to handle multiple URL fields so that all URLs are imported, instead of just the last one.

## Screenshots
Screenshot 2023-09-25 at 10 26 56 AM

### CODE REVIEW

File: libs/importer/src/importers/safeincloud-xml-importer.ts [hunk 1]
```diff
@@ -82,7 +82,11 @@ export class SafeInCloudXmlImporter extends BaseImporter implements Importer {
           } else if (fieldType === "notes") {
             cipher.notes += text + "\n";
           } else if (fieldType === "weblogin" || fieldType === "website") {
-            cipher.login.uris = this.makeUriArray(text);
+            if (cipher.login.uris) {
+              cipher.login.uris.push(...this.makeUriArray(text));
+            } else {
+              cipher.login.uris = this.makeUriArray(text);
+            }
```
Comment (audrey-jensen) [inline libs/importer/src/importers/safeincloud-xml-importer.ts:89]: It seems to me like this might be better fixed by making the uris member always populated, that way the array would not need to differentiate these two cases--you'd always push into the list.

Given that [LoginView.uris](https://github.com/bitwarden/clients/blob/bb602dfb8da40a18e5cb4293ad9e6724237a88dc/libs/common/src/vault/models/view/login.view.ts#L19) does not include `null` as a valid value in its type signature, I'd recommend that the type be adjusted instead of this point-in time fix. That would, however, potentially break statements that check for uris as on line 85, instead of using the `hasUris` method.

**Review by audrey-jensen — COMMENTED** [review]
@djsmith85 - Since I'm unaware of the implications of my comments, I'm passing this to you to double-check my understanding of the code.

**Comment by sonigeez** [comment]
> It seems to me like this might be better fixed by making the uris member always populated, that way the array would not need to differentiate these two cases--you'd always push into the list.

Thanks for your feedback @audrey-jensen , based on your feedback I have made some changes to always populate uris array

**Review by audrey-jensen — APPROVED** [review]

**Review by LRNcardozoWDF — DISMISSED** [review]
Thank you for your contribution. The change looks good.

**Comment by audrey-jensen** [comment]
@sonigeez - I'm so very sorry for taking so long to get back to you. I've forwarded this PR to QA for testing. My test branch merges the latest from master. 

You can either pull the latest changes from master:
```
# get latest on master in github
git fetch -a origin
git merge master
# take your nullable fix and origin's fido2Credentials
```

Or snag the merge from the QA branch:
```
git remote add upstream # insert your preferred uri method here
git fetch upstream community/PM-4077/safeincloud-multiple-url-fix
git pull upstream community/PM-4077/safeincloud-multiple-url-fix
```

**Comment by sonigeez** [comment]
hey @audrey-jensen I have merged latest changes from master branch.

**Comment by audrey-jensen** [comment]
@sonigeez - Your fix has passed QA! I'll work to get it integrated ASAP.

Unfortunately, while it was going through the queue we had a prettier update. I'll need you to merge in master again, then run the prettier manually. Once that's complete, I'll get it merged ASAP.

```
npm ci && npm run prettier
```

**Comment by sonigeez** [comment]
hey @audrey-jensen i have fixed lined linting for it by running command you mentioned and pushed into the branch
thanks

**Comment by sonigeez** [comment]
hey @audrey-jensen sorry i just checked, i have override my modified code while i was merging master so i have updated that again

**Review by audrey-jensen — APPROVED** [review]
It's the final countdown! bah-dah-da-da! dah-dah-daa-da-daaa...

**Review by LRNcardozoWDF — APPROVED** [review]
